### ISSUE TITLE
Upgrade to Material3

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1009]
- [x] Upgrade to material 3 theme
- [x] Switches have a purple background when ON
- [x] Bottom sheet has an orange tint (should be background color)
- [x] Text inputs are outlined rather than filled (not sure if this is actually an issue - I kind of like the outline view, I'll need to play around with it)
- [x] QR card has an outline
- [x] Buttons should have a shadow
- [x] Metal detector dial color

**Comment by kylecorry31** [comment]
Blocked until material3 has a stable release

**Comment by michaelblyons** [comment]
Can the bottom nav items keep their labels instead of bouncing up to show the label for the selected one?

**Comment by kylecorry31** [comment]
@michaelblyons The Material Design guideline is to show only a single label if the labels are long. In English, for example, they are Navigation, Weather, Astronomy, Tools, and Settings - therefore overlap is likely and only a single label is shown.

Now if the Weather tab isn't available, I could probably fit all the English labels together - so maybe I could show the labels then if the screen is wide enough - I'll look into that, but won't be adding them when all 5 nav items are visible.
