### ISSUE TITLE
"app not installed" on trying to install version 3.0.0

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#1035]
Android version 8.1.0

**Comment by kylecorry31** [comment]
Hi, where are you installing the app from?

**Comment by kylecorry31** [comment]
I just tried installing the APK linked to the GitHub release, and it seems it was missing the native libraries - I just reuploaded it, so it should be working now (if that's where you were downloading it from). 

This APK is a debug version, only posted on GitHub (so the problem won't be present in F-Droid and Google Play once the release rolls out)

**Comment by swedneck** [comment]
Yeah it works now, thanks! I tend to download from github to get updates right away :P
