### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by paulle** [kylecorry31/Trail-Sense#104]
There are two things in the I can't find in the German string for translate. 
The ruler calibration and the waxing (for the moon).
![Screenshot_20200602-134352](https://user-images.githubusercontent.com/4852079/83522813-7d990a80-a4e1-11ea-9f86-7553a86c0845.png)
![Screenshot_20200602-134440](https://user-images.githubusercontent.com/4852079/83522820-7e31a100-a4e1-11ea-81be-c0c51cdc8f3f.png)

**Comment by kylecorry31** [comment]
Hello, I added the German translation (using Google Translate) of the ruler calibration: https://github.com/kylecorry31/Trail-Sense/commit/7161a25d8132917b9fd80450b9d150033513b29a

Does that look correct?

Also, I didn't translate the moon phases though, would you be able to help with that?

The phases in English are:
- Waxing crescent
- Waxing gibbous
- Full moon
- New moon
- Waning crescent
- Waning gibbous
- First quarter
- Third quarter

**Comment by paulle** [comment]
Will try it.
Full moon  Vollmond
New moon  Neumond
First quarter  Erstes Viertel
Third quarter  Drittes Viertel
Waxing gibbous  zunehmender Dreiviertelmond (means: Waxing gibbous moon) in German there is no expression for only Waxing gibbous.
Waxing crescent  zunehmender Sichelmond
Waning crescent  abnehmender Sichelmond
Waning gibbous  abnehmender Dreiviertelmond 
waning  abnehmend
waxing  zunehmend

Hope this will help you

**Comment by kylecorry31** [comment]
Thank you!
