### ISSUE TITLE
publish APK along with releases

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#106]
would this be possible? I haven't gotten any updates from F-Droid so it'd be nice to be able to just grab the APK from the github release page

**Comment by kylecorry31** [comment]
Yeah, F-Droid takes a while - I can definitely post the APK there!

**Comment by kylecorry31** [comment]
Done - I posted an unsigned release build from Android Studio (should be about half the size of the normal debug builds.

**Comment by swedneck** [comment]
Hmm, it seems i'm unable to install the release APK.
Sadly i don't get any sort of error, it simply says "app not installed"... Thanks android!

**Comment by kylecorry31** [comment]
That's odd - maybe it has something to do with a version conflict with the currently installed version. I'll post the debug APK as well, maybe that will help

**Comment by swedneck** [comment]
i thought so too, but even uninstalling the previous version i had doesn't make the newest release work

**Comment by kylecorry31** [comment]
That is odd, let me know if the debug version works

**Comment by swedneck** [comment]
Yeah debug version works, very odd
