### ISSUE TITLE
option to show moon/sun location when down

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#107]

**Comment by kylecorry31** [comment]
This would be on the compass correct?

I'll enable that and play around with it a bit to see how it feels (maybe I can give them a different color when they are down).

**Comment by swedneck** [comment]
Yes, mostly i feel that it's still useful to see the sun's position when it's below the horizon since it can still affect the sky (very obvious during summer in the north).

Giving them a different color sounds like a good solution.
