### ISSUE TITLE
astronomy graph doesn't change when browsing dates

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#109]
IMO it should show the graphs for the currently selected date, probably without the sun and moon shown.

**Comment by kylecorry31** [comment]
Might have a weird edge case if the setting to keep the sun/moon centered is enabled - I'll see what I can do with that (maybe make it so if you are on today view, they are centered, but other than that they don't show up)

**Comment by swedneck** [comment]
Yeah that sounds good
