### ISSUE TITLE
Reference tides (harmonic)

### ISSUE THREAD

**Issue by Lee-Carre** [kylecorry31/Trail-Sense#1102]
Inspired by #1068:

> Have user enter the necessary constituents

Given #1099; supply an in-app list of (well-defined / stable / popular) locations, for convenience. Have them handled similarly to user-input locations; especially if they have the auto-select-nearest preference enabled.

Related:
* #549
* #1072
* #1073

Ideally structure the repository's source data (CSV(s)) such that contributors can easily add their favourite. By all means apply compression at build-time.

**Comment by kylecorry31** [comment]
Things to consider for bundled tides:
- Popularity
- Proximity to a coastal trail (I don't want to add harmonics for areas outside of TS' use cases - unless interpolation can be done #1104 )
- Accuracy with the given HCs that TS will support

**Comment by kylecorry31** [comment]
Added an experimental tide model that will be available in 6.6.0: #2518
