### ISSUE TITLE
schedule and time mismatch

### ISSUE THREAD

**Issue by OmlineEditor** [kylecorry31/Trail-Sense#1113]
the lines match for sunset and moonrise, but the time difference is 1 hour. please correct the graphs and time so that they match everywhere.

![bug](https://user-images.githubusercontent.com/13348933/148254650-6b0c880a-6b67-416b-b41c-7b219552c282.jpg)

**Comment by kylecorry31** [comment]
Hi, this might be an issue where your location isn't set up, so it doesn't know which location to calculate the times for (see the "GPS isn't working or sunrise/set times are inaccurate" of the FAQ: https://github.com/kylecorry31/Trail-Sense#faq) 

Let me know if that helps

I'll also double-check that the graph is displaying properly when the location is set up before closing this.

**Comment by OmlineEditor** [comment]
after specifying the location and turning on the GPS, the problem is not solved

![bug2](https://user-images.githubusercontent.com/13348933/148269150-c45bb504-ce7b-44be-9fd2-3fe41e9841af.jpg)

**Comment by kylecorry31** [comment]
Okay, thank you - I will look into it.

**Comment by kylecorry31** [comment]
Thanks for catching this - I was able to reproduce the issue (the horizon line isn't perfectly centered on the chart) and will fix it in the next release (this weekend). 

The times which are shown and altitudes when you tap the sun/moon icon are accurate though.
