### ISSUE TITLE
Add dirty check for creating tide table

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1127]

**Comment by Lee-Carre** [comment]
> dirty check

* the data is too-far-out-of-date? (If so, I had an idea.)
* the data has invalid-syntax?
* something else?

**Comment by kylecorry31** [comment]
The dirty check is a bit different than that - it's just "has the user changed any information for the tide table". This is the dialog you get if you try to back out of a tide table after making changes, but not saving.
