### ISSUE TITLE
Lightning strike distance history

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1144]
- [x] When the user gets a lightning strike distance, record the distance and current time
- [x] Display the last lighting strike
- [x] Delete readings older than a few hours

**Comment by JensKorte** [comment]
Can the strike history be used for weather prediction?

**Comment by kylecorry31** [comment]
Here are the things I think it could tell:
- If there is a storm
  - This wouldn't be useful though as you are using this tool because there is a storm (i.e. no added information)
- If the storm is moving closer or further from you
  - This would be useful as the speed and time of arrival/clearing up could be shown: https://github.com/kylecorry31/Trail-Sense/issues/1240 
- The intensity of the storm (frequency of lightning strikes - more research would be needed)
  - Similar to if there is a storm, this wouldn't really add any information the user isn't already aware of
