### ISSUE TITLE
Show labels for nav items (if room)

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1167]
Moved here from @michaelblyons on https://github.com/kylecorry31/Trail-Sense/issues/1009

This should be a setting, like the Compact mode setting - but I'm not sure if this should be added since I'm planning on allowing the user to customize the bottom navigation items (and some names are long). It could truncate, but that probably won't look great.

**Comment by Lee-Carre** [comment]
From a UX perspective, labels will help with discoverability, especially for newbies.

Ideally, icons would be perfectly obvious, but that's not easy to accomplish. Designs would need to be user-tested.

Perhaps make it depend on orientation; when landscape, show all. When portrait, show only currently selected.

**Comment by kylecorry31** [comment]
Not going to implement.

- Clutters the UI
