### ISSUE TITLE
Incorrect Chinese translation: Pressure

### ISSUE THREAD

**Issue by mellvie** [kylecorry31/Trail-Sense#1173]
In China,the "pressure" has many meanings.It is important to distinguish "压力" and "压强".So there is many error between "压力" and "压强".

**Comment by kylecorry31** [comment]
Hi, I will take a look at the Chinese translation for pressure this afternoon and update it - thanks!

**Comment by kylecorry31** [comment]
@mellvie Thanks, I have replaced all references to "压力" with "压强" and it will be included in the next release.
