### ISSUE TITLE
Calculate exact time of moon phase

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1188]
Rather than scanning every minute, implement an algorithm to calculate the exact time of the moon phase (used for searching for the next full/new moon and supermoon)

**Comment by Lee-Carre** [comment]
For reference (or inspiration): [Suntimes](/forrestguice/SuntimesWidget) uses a variety of libraries to perform the astro calculations.

**Comment by kylecorry31** [comment]
@Lee-Carre thanks! I have a book for astronomical algorithms which I have been using to create the Sol library for Trail Sense, but will take a look at that as well

**Comment by kylecorry31** [comment]
Replaced by #1921
