### ISSUE TITLE
Handbook. Guide. Extra info

### ISSUE THREAD

**Issue by Ygarr** [kylecorry31/Trail-Sense#1192]
How about add some rope knots examples to handbook.
Usually it is enough 15 kinds of knots to use in everyday life.

**Comment by kylecorry31** [comment]
Hi, thank you for the suggestion - unfortunately, I want to stay out of having reference information in Trail Sense in favor of having all tools be sensor-driven (the cloud tool is currently an exception to that - but it will soon be replaced by the Cloud Scanner once that leaves experimental mode). My recommendation for survival reference information is the Offline Survival Manual app that can be found in the "Recommended apps" guide.
