### ISSUE TITLE
Bubble level: Calibration/configuration for devices for with non-flush backs

### ISSUE THREAD

**Issue by t-8ch** [kylecorry31/Trail-Sense#1217]
Some devices (like the Google Pixel 6) have protruding cameras on the back.
This leads to incorrect sensor readings.
While it is possible to work around this but placing the phone at the edge of the area to measure, using only the flush side of the device, this may not be possible on all occasions.

It may make sense to provide a way to configure or calibrate the bubble level functionality.
Having a static database of corrections could be problematic as different cases can also change the required corrections.

**Comment by kylecorry31** [comment]
Thanks for the suggestion - the calibration of the bubble level will be completed by this issue: https://github.com/kylecorry31/Trail-Sense/issues/1025

(I'll update the description to mention the bubble level so it appears in search)

**Comment by t-8ch** [comment]
Thanks!
