### ISSUE TITLE
Show when sun and moon reach peak position

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#125]

**Comment by paulle** [comment]
This would be a good feature.

**Comment by kylecorry31** [comment]
I will add a 'more' button to the astronomy page where some of the following info can be found (or just make the details list scrollable - have to see what looks better):
- Solar noon
- Solar midnight (not sure how important)
- Lunar noon
- Lunar midnight (not sure how important, or what it is called - got to do some research here)
- Moon illuminance (remove from phase name in regular UI)
- Tidal information (whether it is a neap, spring, or average tide - not sure how important)
- Sun/moon altitude (degrees)

All values will respect the selected day, except when on the current day where they will reflect the value at the exact time.
