### ISSUE TITLE
No monitoring weather in background option?

### ISSUE THREAD

**Issue by programmin1** [kylecorry31/Trail-Sense#126]
It isn't clear in the app what the "Monitoring weather in the background" is. And with the altimeter/barometer setting, I'm not sure my phone even has a barometer?? It would be good to have an option to turn that off as I see it uses power.

It would also be great to remind us to do the figure 8 move to make the phone compass accurate as it doesn't work initially.
That's my feedback.. thanks for a nice looking app!

**Comment by kylecorry31** [comment]
Hello, you can disable the monitoring with the "Monitor weather" setting. As per your other comments, there is an ongoing issue to provide calibration which should handle them. Thanks for the feedback!

![Screenshot_20200711-061604](https://user-images.githubusercontent.com/5938560/87221989-36066980-c33e-11ea-99e2-f17c93eaae92.png)
