### ISSUE TITLE
Using incorrect Lang-code for Hebrew

### ISSUE THREAD

**Issue by tzagim** [kylecorry31/Trail-Sense#1268]
The language code in Android is the old Hebrew language code, so IW is used instead of HE.
It seems possible to create a symlink from values-iw to values-he and it will work.
Therefore, it does not display Hebrew to the user.

Thank you for your amazing work.

**Comment by kylecorry31** [comment]
Thanks for letting me know, I will fix this for the next release

**Comment by kylecorry31** [comment]
I have committed a fix into main (therefore it will show up in Weblate), and will include this in the next release (in a few weeks)
