### ISSUE TITLE
Setting: english language

### ISSUE THREAD

**Issue by rudolfmu** [kylecorry31/Trail-Sense#1311]
Please add a setting to use the app in english, regardless of system setting.

This helps when discussing the app in forums, which are mostly english.
The user guide is in english, the Survival Guide is in english.
Not every translation makes sense.

I am aware of issue  #403, but my suggestion should be easier to implement in the short run.

**Comment by kylecorry31** [comment]
Hi, thank you for the suggestion. If there are translations with do not make sense, please let me know and I will try to update them or make a note in weblate to have them fixed. 

In my opinion this has the same complexity (as in it would be the same solution for both) and priority as https://github.com/kylecorry31/Trail-Sense/issues/403 so I am going to close it in favor of that.
