### ISSUE TITLE
Companion app: Walkie talkie

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1320]
Can communicate with nearby users/people you've connected with over Bluetooth or wifi direct.

**Comment by JensKorte** [comment]
There is a feature request in briar which is about the same, but briar doesn't support wifi direct but bluetooth and local network (and encrypted connections via tor). The maximum blocksize in briar is 32kB and multiblock hasn't been implemented yet https://code.briarproject.org/briar/briar/-/issues/2361

**Comment by kylecorry31** [comment]
Closing in favor of https://github.com/kylecorry31/Trail-Sense/issues/1540 and https://github.com/kylecorry31/Trail-Sense/issues/1715
