### ISSUE TITLE
Label compass with magnetic vs true north

### ISSUE THREAD

**Issue by gdt** [kylecorry31/Trail-Sense#1347]
I know that there is a setting for magnetic vs true, but I returned to Trail Sense after long enough that I didn't remember how I had set it.  It would be nice if  the compass readout showed "335\deg T  NW" or "335\deg M  NW" depending on the option.

**Comment by kylecorry31** [comment]
Good idea - I'll experiment with the text / icon to see what works best.

**Comment by kylecorry31** [comment]
Also add this badge to the bearing input view

**Comment by kylecorry31** [comment]
Maybe show an icon (magnet vs globe), when tapped shows that it is magnetic or True North. 

I don't think abbreviations will work (would be confusing and not great for localization), and the text is too long to show by itself.

**Comment by gdt** [comment]
Magnet vs globe makes sense.   The UI style of an icon and then a help method to get a proper, not contrained to be too short, localized text sounds great to me.

**Comment by kylecorry31** [comment]
Tasks:

- [x] Show north reference on navigation tool
- [ ] Show north reference on bearing input view
- [ ] When north reference is clicked on the navigation tool, show a dialog about what is being used and link to settings to change it
