### ISSUE TITLE
how to measure lightning distance

### ISSUE THREAD

**Issue by blogdemoi** [kylecorry31/Trail-Sense#1355]
Hi,

how to measure lightning distance using this application?

Thank you.

**Comment by kylecorry31** [comment]
@blogdemoi Hi, you can measure lightning distance using the "Lightning Strike Distance" tool. With the tool open, tap the Lightning button when you see lightning and tap it again (button name changed to "Thunder") when you hear thunder.

**Comment by blogdemoi** [comment]
Thank you, very easy indeed. And a useful application.

**Comment by kylecorry31** [comment]
Thanks!
