### ISSUE TITLE
Use pedometer to estimate location from last known GPS fix

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#142]

**Comment by kylecorry31** [comment]
Closing this - the location calculated through this method would not be accurate since you only have a distance and a user chosen direction - it doesn't account for non-linear distance or backtracking.

**Comment by aw-bib** [comment]
> the location calculated through this method would not be accurate since you only have a distance and a user chosen direction - it doesn't account for non-linear distance or backtracking.

Agree, it is an _estimate_ only. Ideally, one has some way to correct the dead reckoning position later on e.g. by bearings.
