### ISSUE TITLE
Bubble level precision

### ISSUE THREAD

**Issue by JonnyTech** [kylecorry31/Trail-Sense#1423]
Is is possible to display a greater accuracy with bubble level similar to other apps?

![Screenshot_20220815-133547](https://user-images.githubusercontent.com/3584732/184636860-f6eba0d3-f7ee-44f8-9ebe-4cd61927b24e.png)

![Screenshot_20220815-133557](https://user-images.githubusercontent.com/3584732/184636923-a2a0da50-ebed-4ba7-b782-1cde8b1debcd.png)

**Comment by JonnyTech** [comment]
Thank you for your consideration. I am using it to show the kids how to build booby traps for protection when outdoors so it is kinda within the use case ;)

**Comment by kylecorry31** [comment]
Actually, it doesn't hurt to add it and it is pretty easy to add now, so I'll just do that for the next release (I already have changes to the bubble level in the release, so it won't add much extra testing)

**Comment by JonnyTech** [comment]
Brilliant - thank you!
