### ISSUE TITLE
An interesting old app: Mapever

### ISSUE THREAD

**Issue by vinniec** [kylecorry31/Trail-Sense#1457]
when I saw your app I immediately thought of an old app which unfortunately no longer works on new devices but which could give you a good idea for an additional tool. 

https://f-droid.org/en/packages/de.hu_berlin.informatik.spws2014.mapever/

 It simply allows you to create an amorphous gps map based on the points entered, so it allows for example to navigate on a hand drawn map with all the wrong dimensions.  When it worked it was great.

you could create a tool to draw a map by hand by inserting both drawings without reference points and reference points and then you could insert the function to normalize the map according to the real proportions of the distances inserted with the gps.  a kind of handmap creator

**Comment by kylecorry31** [comment]
Thank you for the suggestion! I actually received a recommendation to take a look at this app shortly after Trail Sense's offline maps were created - unfortunately, I couldn't run it on my device either, but I looked at the source code for it and saw it uses a different algorithm than I do to calibrate map images. I created the following issue to investigate using a similar algorithm: https://github.com/kylecorry31/Trail-Sense/issues/1330 (this issue should now be linked there for reference)

**Comment by vinniec** [comment]
thanks for the appreciation
