### ISSUE TITLE
Make geo location format a config option

### ISSUE THREAD

**Issue by scalvin1** [kylecorry31/Trail-Sense#146]
It would make the app a lot more useful if the location format (for beacons) could be configured.
It proved to be less hassle when going between devices, tools and apps, to simply give location by two floating point numbers rather than the traditional degree,minutes,seconds.decimal.

My preferred format has always been latdeg.decimals, londeg.decimals.

Otherwise a promising app. Have not found anything else that comes close to the old simple clean useful navigation provided by first generation hand-helds, like the Garmin Geko 201, or 301!

All I want from a nav app is to tell me direction and distance to a point (or some points) which are easily input and edited.

Thanks and best regards,
Susan Calvin

**Comment by kylecorry31** [comment]
Thank you for the feedback!

I have a few other things I want to get into the next release, and this setting is one of them.
