### ISSUE TITLE
Research Wear OS support

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1467]
- [ ] Determine steps needed
- [ ] Determine which features would make sense to port

**Comment by rmnwnsx** [comment]
As you said, there are some people, who want this feature, and you need time and device to port and test Wear OS app. Maybe you can make a goal or tier in github sponsors specifically for porting to wear os and this people can donate to you.

**Comment by kylecorry31** [comment]
@rmnwnsx thank you, that is a good idea - I have several major features which I want to ensure are finished first within Trail Sense before I commit to adding a goal/tier for that. But once those are done and I confirm it is feasible to do, I can create a tier.

The major feature roadmap (with tentative dates) is outlined here: https://github.com/kylecorry31/Trail-Sense#feature-roadmap

**Comment by kylecorry31** [comment]
Unfortunately, I will not be adding this. The time and effort is too much for me to make the port and I don't have a smart watch (nor do I plan to get one)
