### ISSUE TITLE
bottoms placement

### ISSUE THREAD

**Issue by paulle** [kylecorry31/Trail-Sense#150]
![image_2020_08_23_19_13_41](https://user-images.githubusercontent.com/4852079/90984417-17b69f00-e575-11ea-9bfa-fc9d3f7af4b0.png)
Maybe the ruler button would be placed above the level icon and the button for adding a beacon between level and velocity.
Using xperia5, android 10

**Comment by kylecorry31** [comment]
Thanks, I'll look into some options here (and may only apply them on smaller screens)
