### ISSUE TITLE
Astronomy does not work correctly when switching from dst

### ISSUE THREAD

**Issue by GlowingUmbreon** [kylecorry31/Trail-Sense#1518]
![Screenshot_20221030-174357_Trail Sense](https://user-images.githubusercontent.com/37640997/198893452-6f4e6ca0-7098-45d4-ac8e-633cf22960b9.png)
The UK has left daylight saving time today and the astronomy section is noy showing the full amount of info.

**Comment by kylecorry31** [comment]
Thank you for reporting this, I will look into it - though by the time I have a fix in place, the problem date will have already passed (I'm assuming the second screenshot is it working fine tomorrow - it doesn't appear to have uploaded correctly).

**Comment by kylecorry31** [comment]
This will be fixed in the next release, thanks for opening this ticket and providing all the needed info!
