### ISSUE TITLE
Shutter button off screen

### ISSUE THREAD

**Issue by Eltrits** [kylecorry31/Trail-Sense#1521]
When I try to take the picture of a cloud I can't do it because the button is outside of the screen:
![signal-2022-11-03-11-34-08-652.png](https://user-images.githubusercontent.com/67630973/199699359-833bd816-281a-451e-8173-66c2f7e7de2a.png)

**Comment by kylecorry31** [comment]
Thank you for reporting this, I'll make some adjustments to try and fix that

In the meantime, you should be able to take a picture with your phone's camera app, and then scan the cloud from a file instead.

**Comment by kylecorry31** [comment]
The fix for this will be in the upcoming release (probably this weekend)
