### ISSUE TITLE
Flashlight Tile

### ISSUE THREAD

**Issue by xmha97** [kylecorry31/Trail-Sense#1554]
Please add the flashlight tile (like Xiaomi phones)

![Screenshot_2022-11-23-01-01-10-278_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/203425403-cd121fc4-de6d-450a-9344-c4ac39c0cf0e.jpg)

**Comment by kylecorry31** [comment]
Thank you, good idea - I forget the original reason why I didn't add it (maybe it was something about it not picking up when you enable it from the system - if so, I think I have that fixed).

**Comment by kylecorry31** [comment]
Moved to https://github.com/kylecorry31/Trail-Sense/issues/2120
