### ISSUE TITLE
Compact astronomy view

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1575]
Investigate ways to make a compact mode for astronomy - such as merging rise, set, and transit into a single item (like a table view). Available as a setting, default off.

**Comment by JensKorte** [comment]
Maybe this is a good topic for a beginner. I didn't find the icons for moon and sun, just replace them

```
        ⮉               ⭱              ⮋
S 6:49 AM 12:34 AM 6:19 AM
          ⮋            ⮉           ⭱ 
M 2:42 AM 5:12 PM 10:30 PM

       Civil Nautical Astronomical
S ⮉ 
S ⮋

S  ⏲ (or Daylight)
```

**Comment by kylecorry31** [comment]
Thanks, that looks to be a pretty clear UI - I like the use of icons, that will help on small screen devices.

**Comment by kylecorry31** [comment]
Replaced by #1794
