### ISSUE TITLE
Missing translation German (not in the string)

### ISSUE THREAD

**Issue by paulle** [kylecorry31/Trail-Sense#160]
This is a screenshot from the astronomy tab.

![Screenshot_20200826-100505](https://user-images.githubusercontent.com/4852079/91329899-02d24980-e7c9-11ea-9b7f-daad8477a8ea.png)
It should be    bis Sonnenuntergang   not  bis sonnenuntergang

These are some screenshots from the configuration tab.
![Screenshot_20200826-100619](https://user-images.githubusercontent.com/4852079/91330199-65c3e080-e7c9-11ea-92c4-f41943bc8fd1.png)
Monitor weather      Wettermonitor
in the background     im Hintergrund
Forecast Sensitivity  Vorhersagegenauigkeit

![Screenshot_20200826-100643](https://user-images.githubusercontent.com/4852079/91330783-2c3fa500-e7ca-11ea-8654-4c2c321ad198.png)
Keep sun/moon centered     Sonne/Mond zentriert lassen
When up                              Wenn aufgegangen

![Screenshot_20200826-100725](https://user-images.githubusercontent.com/4852079/91331261-da4b4f00-e7ca-11ea-8625-327b496c686c.png)
When up                              Wenn aufgegangen
Never                                  Nie
Always                                Immer

**Comment by kylecorry31** [comment]
Thanks! It's hard keeping up with translations, especially because I can only really verify English and a tiny bit of Spanish - always afraid Google Translate will translate to something bad/completely wrong.

**Comment by paulle** [comment]
Yes, Google translate produces from time to time very strange translations. For me it won't matter to translate/correct the string when a new version with additional text is out, but I don't know how to get access to text not included in the string.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
