### ISSUE TITLE
[Suggestion] FM Radio support

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1701]
A user suggested I add FM Radio support if the device has the hardware. Unfortunately, none of my devices have that capability, and I'm not sure Android exposes functionality for that. 

This issue is to research whether this would be possible, and how I would be able to test it if it is.

**Comment by xmha97** [comment]
You can support internet radio feature.
For example: https://radio.rpscloud2.ml/pop

**Comment by kylecorry31** [comment]
@xmha97 thank you for the suggestion. Trail Sense does not have the Internet permission, so if I implement this feature I would only be able to support devices with the FM Radio hardware.

**Comment by kylecorry31** [comment]
I conducted some research into this - there is no official Android API for doing so, and my device does not have FM Radio support, so I would be unable to verify any unofficial solution using hidden APIs.
