### ISSUE TITLE
Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [kylecorry31/Trail-Sense#1706]
Please support the Android 13 Themed App Icons feature.

![Screenshot_2023-03-23-17-38-26-778_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/227277379-02092990-41c7-48d4-8161-9b326e574c20.jpg)

**Comment by kylecorry31** [comment]
Good idea - I was not aware of the monochrome icons on Android 13, and will add that.

**Comment by xmha97** [comment]
Thanks 🙏
