### ISSUE TITLE
App recommendation: Briar

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1715]
For offline communication

https://play.google.com/store/apps/details?id=org.briarproject.briar.android

**Comment by michaelblyons** [comment]
Bluetooth communication in the woods? Wouldn't you be within earshot for it to work? Maybe helpful for hearing impairment, I guess.

**Comment by kylecorry31** [comment]
Hi, the Walkie Talkie idea was a user suggested feature - I haven't done much research into its practicality (ex. range) yet.

https://github.com/kylecorry31/Trail-Sense/issues/1540 documents other users of bluetooth that could be possible, such as offline file sharing or shared navigation.

**Comment by michaelblyons** [comment]
@MikaelaLovett You may be interested in this issue. Briar doesn't currently do voice, but they have an [issue discussing it](https://code.briarproject.org/briar/briar/-/issues/985). The nice thing is that they switch between communication modes.

I also found an app called "WalkieDroid," that purports to do Bluetooth push-to-talk, but I have not tried it.

**Comment by MikaelaLovett** [comment]
> @MikaelaLovett You may be interested in this issue. Briar doesn't currently do voice, but they have an [issue discussing it](https://code.briarproject.org/briar/briar/-/issues/985). The nice thing is that they switch between communication modes.
> 
> I also found an app called "WalkieDroid," that purports to do Bluetooth push-to-talk, but I have not tried it.

Ohh thank you very much, I'll check it out!! 💗
