### ISSUE TITLE
Change system navigation bar color based on theme

### ISSUE THREAD

**Issue by nvllz** [kylecorry31/Trail-Sense#1747]
Apply dark and black themes to the navigation bar. Currently it's always white, regardless of the theme setting.

**Comment by kylecorry31** [comment]
@nvllz Hi, I'm sorry you are having issues with Trail Sense. Can you provide me the following information:

1. What version of Trail Sense are you seeing this on? (Trail Sense Settings > Version)
2. What version of Android is your phone running? (System Settings > About phone > Android version)
3. If possible, can you upload a screenshot of the issue you are seeing?
4. By navigation bar, are you referring to the Android navigation bar (ex. back, home) or Trail Sense's navigation bar (Navigation, Weather, Astronomy)?
 
 
I use the dark theme on my device without issues (Pixel 5A, Android 13, Trail Sense 4.17.0). On mine, Trail Sense's navigation bar changes color based on the theme, while the system navigation bar is always black with white icons.

**Comment by kylecorry31** [comment]
Thanks - currently Trail Sense doesn't change the color of the system navigation bars, I'll log this as a feature request.
