### ISSUE TITLE
Add tendency indicators to pressure graph

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#179]
- [ ] Display tendency as X / 3 hr when the graph is clicked
- [ ] (optional) Show tendency as a tangent line on the graph

**Comment by aw-bib** [comment]
An option would also be to construct the tangent line at the given (=clicked) point using the derivative of the curve, or more likely dx/dy using two points of the graph. Giving it a long line would make the tendency quite clear, probably also adding some number at the end.

**Comment by kylecorry31** [comment]
I like that, thanks!

**Comment by kylecorry31** [comment]
Not going to implement this.

Reason:
- Frequency of use (ex. edge case) vs effort to implement
- Clutters the UI
