### ISSUE TITLE
Don't reduce map quality from the original image

### ISSUE THREAD

**Issue by jptrzy** [kylecorry31/Trail-Sense#1799]
My map image normally takes ~17mb, but after adding it as a photo map, it shows only ~3mb (in the app).

The quality of this map (inside the app) is visibility worsen, then the original image.

*I used the **change resolution** option, but it didn't anything in a visible way.*

### Specs
App Version: 4.18.0
Android Version: 13

**Comment by kylecorry31** [comment]
Thank you for the details - there were some technical aspects that required me to reduce the resolution during the cropping step to avoid crashing on most phones. I'll double check that the "Reduce map resolution" setting is properly working when the map is not cropped before I release the Photo Map tool, and add some descriptive text there to call that out.

I'm going to close this issue in favor of this one: https://github.com/kylecorry31/Trail-Sense/issues/1033
