### ISSUE TITLE
AR sun/moon - link to astronomy tool

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#1802]
- [x] Add a 3D button to the sun/moon chart that links to the AR tool (if enabled) - with the astronomy mode activated
- [x] Use augmented reality view
- [x] Draw line for sun / moon path (experiment with different styles)
- [x] Show time, elevation, bearing, moon phase when hovering over a point
- [x] Render full above horizon path (no breaks): if object is currently down and is less than 6 hours from the next rise, show the path starting at the next rise until next set
- [x] Show a selector at the bottom of the screen to track sun / moon (when navigating from astronomy). Have a clear button to leave astronomy mode (only shows astronomy objects when in astronomy mode)

This requires #1702 to be completed

**Comment by michaelblyons** [comment]
It occurs to that you could put time-stamped markers on the prediction arc. That could help a user picture things like

- When the setting sun will reach the western mountains (ie non-horizen sunset).
- When the moon will rise above the trees.

Obv you could also mark degrees and peak, but the time aspect might be particularly useful.

(Apologies for the suggestion if this is already in the build. I haven't tried the nightly.)

**Comment by kylecorry31** [comment]
Good idea, I'll add that - I have a text indicator for the "focused" (centered) AR point, I'll include the time, elevation, and bearing in that and look into maybe displaying a couple of the times directly over the camera.
