### ISSUE TITLE
Beacon icon: Music note

### ISSUE THREAD

**Issue by michaelblyons** [kylecorry31/Trail-Sense#1821]
Can you please add a music note to the list of icons for beacons? 🎵 or 🎼 or something?

**Comment by kylecorry31** [comment]
Sure, I will add that

Can you also clarify what the music note would mean in terms of a location? I want to make sure I choose a standard map icon if that exists.

**Comment by michaelblyons** [comment]
Several uses, at different scales:

- Bandstand(s) at a big music festival.
- Dance hall at a sleepaway dance camp.
- Group campsite where a spot is designated for musical campers to have a jam session (far enough from tents for others to sleep). 😉

**Comment by kylecorry31** [comment]
Thanks!
