### ISSUE TITLE
Astronomy data may overlap on small screens

### ISSUE THREAD

**Issue by paulle** [kylecorry31/Trail-Sense#183]
Something is overwritten (v0.7). See screenhot.
sony xperia5, android10
![Screenshot_20200903-143431](https://user-images.githubusercontent.com/4852079/92122061-4a755880-edfb-11ea-8340-b44769d5b229.png)

**Comment by kylecorry31** [comment]
Thanks, I'll look into adding an alternative layout for small screens here.

**Comment by kylecorry31** [comment]
This has been fixed in the new release (0.7.1)

**Comment by paulle** [comment]
Thank you, you are realms fast.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
