### ISSUE TITLE
Add map grid to lat,lng calculator

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#184]
Converts a point from a map grid format (ex. USNG) and then allows you to create a beacon from it

https://earth-info.nga.mil/GandG/coordsys/grids/1Sheet_USNGInstruct_v3.pdf

Can be located under the "tools" tab

**Comment by aw-bib** [comment]
For the UK Ordnance Survey Grid (OS Grid) would come in very handy given all hiking maps there are based on that. See e.g. https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid

**Comment by kylecorry31** [comment]
Closing in favor of smaller issues that break this down
