### ISSUE TITLE
Add full share menu to current location

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#188]

**Comment by paulle** [comment]
Something like: 
I'm here...Coordinates...Time
for sending this with threema, signal, telegram, sms or whatever.

**Comment by kylecorry31** [comment]
So, I imagined that this will be the same share menu as can be found on the select beacon page (with the options related to just beacons removed).

I'm also going to add an option to share coordinates (to both beacon list and navigation tab) because TS only has the option to copy coordinates right now.
