### ISSUE TITLE
Indicate when GPS is acquiring lock

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#189]

**Comment by aw-bib** [comment]
One could also think of hooking up with tools like [SatStat](https://www.f-droid.org/en/packages/com.vonglasow.michael.satstat/) to load off the display of satellites etc. similar to the function in OsmAnd.

**Comment by paulle** [comment]
There is another fine app on f-droid which provides a lot of GNSS information if needed or wanted.
https://f-droid.org/de/packages/com.android.gpstest.osmdroid/
A simple hint popping up within Trail Sense, that a lock is acquired would be fine.

**Comment by kylecorry31** [comment]
Yeah, I think for now I'll just put a pop up which says the lock was acquired (and make the accuracy reading say 'Aquiring lock' or something like that)
