### ISSUE TITLE
Translated Sucsessfull

### ISSUE THREAD

**Issue by Craftefix** [kylecorry31/Trail-Sense#1932]
I completed the german Translation.
Can somebody look over it?
Ich habe die deutsche Übersetzung vervollständigt
Kann jemand nochmal darüber gucken.

Craftefix

**Comment by kylecorry31** [comment]
Thank you, I'll merge the weblate pull request now.

**Comment by Craftefix** [comment]
when is the german update comming?

**Comment by kylecorry31** [comment]
I do releases about once a month (normally on a weekend).

For this specific change, it was included in this morning's release.
