### ISSUE TITLE
Compatibility with BLE LoRa Communicators

### ISSUE THREAD

**Issue by LolloDev5123** [kylecorry31/Trail-Sense#1961]
Add an experimental feature that allows TS users to connect their device to a BLE mesh off-grid communication device like https://meshtastic.org.
There's already an android app for meshtastic, but it'd be very cool to see intertwined TS features like sensor readings, backtracking, weather, waypoints, chat, etc. incorporated with meshtastic (see meshtastic telemetry features, this allows for "remote" barometers, all connected by mesh)

EDIT:
This should be a neat list of what I hope will be implemented
- Connection & Configuration of BLE Meshtastic Devices
- Chat & Channels Support
- Display other mesh devices' location as waypoints
- Ability to use remote telemetry data (like the barometer) from other mesh devices if possible
- Ability to share sensor data from the phone (like the barometer) to the connected device to be used for telemetry 

![image](https://github.com/kylecorry31/Trail-Sense/assets/26120324/618b6239-7e9c-4a16-b548-0efc7e9ef664)
![image](https://github.com/kylecorry31/Trail-Sense/assets/26120324/584492d5-e1fc-4d23-b675-e567ff032be8)
![image](https://github.com/kylecorry31/Trail-Sense/assets/26120324/cfd9fe65-fbed-4dc7-bb23-d82012c43531)

**Comment by kylecorry31** [comment]
Thank you for the suggestion, I will consider adding this along with https://github.com/kylecorry31/Trail-Sense/issues/1540 and https://github.com/kylecorry31/Trail-Sense/issues/1534

**Comment by msherba** [comment]
Meshtastic app offers the imeshservice to interface with the hardware devices. For an example of a plugin using it see the Meshtastic ATAK-Plugin which takes CoT messages from ATAK and sends them over the Meshtastic device paired via Bluetooth in the MT app.

**Comment by kylecorry31** [comment]
Moved to https://github.com/kylecorry31/Trail-Sense/issues/1540 to tidy things up for now
