### ISSUE TITLE
Translation error on weblate

### ISSUE THREAD

**Issue by Craftefix** [kylecorry31/Trail-Sense#1965]
Hello i cant edit the german weblate sentences because nobody can save the Translation but german got only 97% translate because of the new update

**Comment by kylecorry31** [comment]
Hi, Weblate appeared to be having some issues this morning (I was getting 404s trying to load the page).

I'm not sure if there are still any ongoing issues on their end, but I've updated the Trail Sense repo there and translations appear to be unlocked. Can you try again?

**Comment by Craftefix** [comment]
![Screenshot_2023-09-16-15-06-53-476_com.android.chrome.jpg](https://github.com/kylecorry31/Trail-Sense/assets/122538317/ad001b35-a9a0-4f25-95e1-dcacc2abfb41)

Look i cant click that button to save and continue and the button for save and stay is completly missing

**Comment by kylecorry31** [comment]
Hi, the app_name is marked as not translatable. That is intended, and was marked as such a few years ago.

**Comment by kylecorry31** [comment]
Here's what I have for filters:
![image](https://github.com/kylecorry31/Trail-Sense/assets/5938560/4431b2ff-e28d-43d1-aea3-12ed84153f4c)

**Comment by kylecorry31** [comment]
So looks like the filter should be: state:<translated instead of state:>=translated

**Comment by Craftefix** [comment]
oops, now i can translate more, thanks for your help

**Comment by kylecorry31** [comment]
Thank you for providing translations!
