### ISSUE TITLE
[Question] Is there dead reconning?

### ISSUE THREAD

**Issue by andrei-akopian** [kylecorry31/Trail-Sense#2086]
Does this app support dead reconning (calculating location based on speed/acceleration and time)?

**Comment by kylecorry31** [comment]
Hi, Trail Sense does not support dead reckoning. See https://github.com/kylecorry31/Trail-Sense/issues/370 and https://github.com/kylecorry31/Trail-Sense/issues/142 for more information.

**Comment by kylecorry31** [comment]
I've also just added https://github.com/kylecorry31/Trail-Sense/issues/2087 for the conversion of speed and time to distance
