### ISSUE TITLE
Settings user guides

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2130]
- [x] General Settings (Units, Theme, Privacy, Errors, Backup / Restore)
- [x] Sensors > Compass
- [x] Sensors > GPS
- [x] Sensors > Altimeter
- [x] Sensors > Barometer (rewrite)
- [x] Sensors > Thermometer (rewrite)
- [x] Merge sensors settings into a single guide

Basically the same as the tool guides in https://github.com/kylecorry31/Trail-Sense/issues/2074

**Comment by VeslaZ** [comment]
I was thinking this morning about an AI assisted tool that could work with
the GPS locator. It would recognize location and give information based on
that location. I.e. animals, foliage, poisons, etc. it would generate
important information about the location and give recommendations based on;
season, etc.
Kind regards,
Will

**Comment by kylecorry31** [comment]
@VeslaZ thank you for the suggestion - I have considered a similar topic with #459 for tool recommendations. Unfortunately more detailed information such as animals, plants, geography, etc would not be feasible without using the Internet (or taking up a lot of storage space). It could be a good idea for a plugin though (#1540)

Also, for future reference I recommend posting to #1911 instead since that is out of scope of this issue (settings user guide).
