### ISSUE TITLE
Request: Update app icon

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2175]
Update the app icon to be more modern (suggestion was to make it brighter and more attractive).

Not sure if I'm going to do this, since I like the simplicity of the icon - but I want to consider some alternatives before just closing this.

**Comment by michaelblyons** [comment]
I use the Arcticons pack, so maybe I shouldn't weigh in, but I like what you have already. 😉

**Comment by CloneWith** [comment]
the current one is good enough 👍

maybe better with the compass pointing to two corners of the icon, something like this:

![Screenshot](https://github.com/kylecorry31/Trail-Sense/assets/110881926/edf48cf0-2842-4d59-af0d-b5c540d0720f)

**Comment by LeftyDextrous** [comment]
I think the current icon is good, although it occurs to me that it may not distinguish the app from other single-function compass apps.

**Comment by kylecorry31** [comment]
Thank you for the suggestions / feedback. 

It's true that it blends in with other single function compass apps, so if I do change the icon, I'll probably try to incorporate multiple tools into the icon. But, I've come to like the simple icon of Trail Sense, so I'm not sure I want to change it (plus I have a t-shirt for Trail Sense with that icon on it 😆)

**Comment by kylecorry31** [comment]
After further consideration, I will not be changing the icon right now
