### ISSUE TITLE
moon rise and set during day

### ISSUE THREAD

**Issue by go9girl** [kylecorry31/Trail-Sense#2211]
Sry if this has been reported already.
The time for the moon is completely wrong
![Screenshot_2024-02-07-20-31-44-01_eb74a44e914202e89450cb4cb4dbc4e6](https://github.com/kylecorry31/Trail-Sense/assets/159335355/2336d4d3-235d-4b93-8422-0e072cd4710e)

**Comment by kylecorry31** [comment]
Hi, I just want to confirm that you are all set?

(the times look accurate to me)
