### ISSUE TITLE
Improve build speed

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2244]
I feel like the build speed can be improved and I have made progress on that, I'm just not sure what else to try at this moment. If someone has a suggestion, please let me know (or submit a PR).

**Comment by HidingInEmptySpace** [comment]
Migrate kapt to KSP.

**Comment by kylecorry31** [comment]
Thank you for the suggestions, I'll take a look. TS is already using KSP instead of kapt, but I have not enabled that incremental compilation.

**Comment by kylecorry31** [comment]
I think I have it as fast as I'll get it for now.
