### ISSUE TITLE
Measure Speed without GPS

### ISSUE THREAD

**Issue by vkuehn** [kylecorry31/Trail-Sense#2246]
Hi,

When sitting in a train, und der bridges, in side ships. In cars. I tend to loose the GPS signal. Which one of those cases happen alot when I travel

Could be speed measurement be added  from sensors for these cases ?

**Comment by kylecorry31** [comment]
Hi, without GPS the only accurate way to measure speed is with the pedometer. This will not work in a vehicle, which is an unsupported use case of Trail Sense - the only supported use cases of Trail Sense are hiking, backpacking, camping, geocaching, and wilderness survival.

For more information:
- [Trail Sense Use Cases](https://github.com/kylecorry31/Trail-Sense/wiki/Use-Cases)
- [Pedometer Guide](https://kylecorry.com/Trail-Sense/guide?id=tool_pedometer)
- [Navigation Guide (see Speed section](https://kylecorry.com/Trail-Sense/guide?id=tool_navigation)
