### ISSUE TITLE
Can't scroll on the data accuracy tips screen

### ISSUE THREAD

**Issue by ChildishGiant** [kylecorry31/Trail-Sense#2286]
The "Tips for improving sensor data accuracy" screen says to hit OK to close it but is too large for my screen and doesnt scroll so there's no OK button for me. Luckily back also closes the screen so I can still use the app. ![Screenshot_20240321-125027.png](https://github.com/kylecorry31/Trail-Sense/assets/13716824/58e57964-7a6c-4644-8551-5234e6343196)

I'm running Android 11 on a titan slim

**Comment by kylecorry31** [comment]
I will add a fix for this, thank you for reporting it
