### ISSUE TITLE
F-Droid build crash

### ISSUE THREAD

**Issue by michaelblyons** [kylecorry31/Trail-Sense#2288]
v5.9.0 has some kind of build error.

Something in build gradle about File! being deprecated in Java.

**Comment by kylecorry31** [comment]
Hm, looks like it is trying to compile with Java 11 but TS uses Java 17. I'll investigate

**Comment by kylecorry31** [comment]
Here's the issue on F-Droid to track it: https://gitlab.com/fdroid/fdroiddata/-/issues/3222

**Comment by kylecorry31** [comment]
Looks like F-Droid is in the process of upgrading their servers and build failures are expected right now. I don't know what their timeline is but they said to be patient and the build will be retried once their upgrade is complete: https://gitlab.com/fdroid/fdroiddata/-/issues/3222#note_1828212755

**Comment by kylecorry31** [comment]
The build has succeeded now, just needs to be indexed by F-Droid to appear in their repo (the normal process). So I think this will be all set. If you don't see the build within a week, let me know (I'll also keep an eye on it).
