### ISSUE TITLE
Use sentence casing for all text

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2336]
- [x] User guides (all headings and ensure the references to text in the UI is still correct)
 - [x] Notification titles / channels
 - [x] Any other text in the app that is not covered by those categories

**Tool and quick action names are considered branded names and should remain in Title Case.**

Only update the English text (en-US or the values/strings.xml - no resource identifier) - these changes will flow into weblate for the translation changes.

Do not change the capitalization of the following:
- Acronyms (ex. USNG)
- App name (Trail Sense)
- Backtrack (this is a proper noun)

Note: The capitalization of sun and moon seems to vary, so I'll say just treat it as a common noun (lowercase when in a sentence).

Resources
- https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case
- https://style.mla.org/capitalizing-earth-sun-moon/

**Comment by muryno** [comment]
Are those to be sentence case also or remain title case 

All tool names
Weather Monitor
all quickActions
User guide
Cliff Height
Lightning Strike Distance
Metal detector
White Noise

**Comment by kylecorry31** [comment]
All of those should be left as title case for now (and any other tool)

**Comment by muryno** [comment]
If  User guides (all headings and ensure the references to text in the UI is still correct) is part of what needs to be converted to Sentence case, 

Are there any exception on those.... 
Also thinking, if some needs to stay Title case, wouldn't that look odd as there is no consistency 😀

Photo Maps
 Triangulate Locations
Bubble Level
Water Biold Timer
Light Meter
Solar Panel Aligner
Light Strike Distance
Augumented Reality
Metal Detector
Packing Lists
QR Code Scanner
White Noise
Recommended apps

**Comment by kylecorry31** [comment]
> If User guides (all headings and ensure the references to text in the UI is still correct) is part of what needs to be converted to Sentence case,
> 
> Are there any exception on those.... Also thinking, if some needs to stay Title case, wouldn't that look odd as there is no consistency 😀
> 
> Photo Maps Triangulate Locations Bubble Level Water Biold Timer Light Meter Solar Panel Aligner Light Strike Distance Augumented Reality Metal Detector Packing Lists QR Code Scanner White Noise Recommended apps

Hi, yes for now keep the tool names and quick action names in Title Case in the User Guide - if I decide to make those in sentence case, I will update the guides as well (essentially anywhere in the app that the tool name appears it should be in title case). I'm on the fence on whether those are considered Product/Branded names and haven't come to a decision yet.

**Comment by kylecorry31** [comment]
After further consideration, tool and quick action names should remain in Title Case (how they are today). I may change my mind on some of the quick actions, but for now to maintain consistency, they should not be changed as part of this issue.

**Comment by muryno** [comment]
does it look good now or still needed an update

**Comment by kylecorry31** [comment]
Hi, going tool to tool, I'm still seeing several strings which are in title case, and also the user guides still need to be converted.

Let me know what you plan to do and I can do the rest

**Comment by muryno** [comment]
user guide has tool name which was advices to be in title case....

ill update soon and you can review again

**Comment by kylecorry31** [comment]
Yes mentions of tool names in the user guide should remain in title case. 

For reference, when I say user guides I mean the content of the guides themselves - not the list where you select the guide to view

**Comment by kylecorry31** [comment]
In preparation of the release next weekend, I'm going to be making these changes.

@muryno if you have any in progress changes that you want included, I ask that you submit a pull request in the next day or two
