### ISSUE TITLE
Change "View in 3D" camera behavior (start with or without camera)

### ISSUE THREAD

**Issue by GuiSousa135** [kylecorry31/Trail-Sense#2340]
The 3D View function is very welcome to the app, really amazing, in the future even better for celestial navigation, but I believe it would be better to open 3D View without the camera opening by default, instead it would start with a black background (or even there is the option to change the default behavior in the settings), and if the user wants to use the camera function they would toggle it with the "camera" button. This would be useful to save the device's battery (in my case, I use an old cell phone that uses up a lot when opening the camera, even if I then switch to the black background).

**Comment by kylecorry31** [comment]
Thank you for the suggestion. I think I am more inclined to add an option for this (keeping the default as opening the camera).

Personally, I find it more useful to use to see where the sun is going to set, which is better to use with the camera. At night, it would probably be less useful to have the camera open to see the path of the moon, so I could see maybe even an option to open with camera during the day, but without the camera at night.

For now, I'll add an option to settings to change the default behavior.

**Comment by kylecorry31** [comment]
A setting for this will be available in the 6.0.0 release next month
