### ISSUE TITLE
Use Accelerometer in some way to smooth out GPS speed readings?

### ISSUE THREAD

**Issue by 7eventech77** [kylecorry31/Trail-Sense#2350]
This may have already been asked but was curious if using the accelerometer acceleration would be able to help smooth out GPS speed(and or pedometer? readings) since there is such a lag time. Feel free to tell me if it is not possible in any way, just wasn't sure if this specific aspect was thought of before.

**Comment by kylecorry31** [comment]
Thank you for the suggestion, I have played around with this and plan to implement as part of #1688
