### ISSUE TITLE
Metal detector sound icon missing

### ISSUE THREAD

**Issue by kuba-orlik** [kylecorry31/Trail-Sense#2362]
On some phones the "sound" icon is present for the metal detector (like on pixel 7a with lineage), but on pixel 7 pro with stock android the icon is missing
![Screenshot_20240501-080400_Trail Sense](https://github.com/kylecorry31/Trail-Sense/assets/2697916/1acb9623-6909-45d2-b80e-0266e6086b30)
![IMG_20240501_080557_974](https://github.com/kylecorry31/Trail-Sense/assets/2697916/b46fee8c-53f1-4944-ba8c-36feaf2e3076)

**Comment by kylecorry31** [comment]
Hi, what happens if you open the Whistle tool on the device where the icon does not show up? Does it get an error message?

Can you also confirm that both are running the same version of Trail Sense (Tools > Settings > Version)?

**Comment by kuba-orlik** [comment]
The whistle works fine on the device where the icon doesn't show up - it's loud and clear, no errors. 

In fact the one on pixel 8 was on 5.9.0, not on 5.10.0. Updating the repositories from fdroid helped Apologies for the confusion :pray:
