### ISSUE TITLE
Packing List Feature Ideas

### ISSUE THREAD

**Issue by CallamJ** [kylecorry31/Trail-Sense#2405]
### More ways to import/export packing lists.
These ideas would be in addition to the export features in #1149

**This could include:**
- Copying a packing list to clipboard as plain text.
- Exporting a packing list to importable and human readable + copy/paste safe text. This would be convenient for sharing packing lists via other services such as email/text.

***These could include or not include the current or desired packed amounts.**

### A feature to quickly increment or decrement packed amounts by 1.
- This could be done with an up and down arrow on each item. 
- Tapping the corresponding arrow would increment the item's packed amounts up/down by 1.

**Comment by kylecorry31** [comment]
Thank you for the suggestions, I will add all of these (and will likely split this issue into smaller issues).

**Comment by kylecorry31** [comment]
Updated #1149 to include copy to clipboard and added https://github.com/kylecorry31/Trail-Sense/issues/2406 for the increment decrement buttons.
