### ISSUE TITLE
Tool: Cricket thermometer

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2427]
Sounds odd, but Dolbear's law shows the current temperature can be estimated using the frequency of cricket chirps.

NOAA provides a few resources:
- https://www.noaa.gov/education/explainers/can-crickets-tell-temperature-answer-is-in-their-chirp
- https://www.weather.gov/epz/wxcalc_cricketconvert

And LOC:
- https://www.loc.gov/everyday-mysteries/meteorology-climatology/item/can-you-tell-the-temperature-by-listening-to-the-chirping-of-a-cricket/

NOAA also states that different species of crickets have slightly different frequencies - so maybe vary this by region / let the user calculate/enter their own. Not sure how this holds up across the globe though.

In the future, this could use a microphone to automatically calculate the frequency.

When user taps button, start a counter - they keep tapping as long as they want, temperature will be re-estimated after each tap. If the user goes too long without tapping, then tapping again restarts the count.

In the future, this could use a microphone to automatically calculate the frequency (4800-5000 Hz).
![image](https://github.com/kylecorry31/Trail-Sense/assets/5938560/2ade88d0-1049-4356-be04-217bf1129e19)

**Comment by anaxonda** [comment]
Wow. Great idea.

**Comment by kylecorry31** [comment]
While this is really cool, the accuracy won't be great (within a few degrees if lucky) and would require a lot of audio processing to get somewhat decent results to something a user can feel (temperature). I will not be adding this to Trail Sense, but hopefully someone takes this further and creates an app out of it - that would be really cool
