### ISSUE TITLE
Compass status in Astronomy 3D or Augmented Reality

### ISSUE THREAD

**Issue by astewart77** [kylecorry31/Trail-Sense#2435]
Compass status in the lower left corner is "Good" in the Navigation tool and Diagnostics are all good.

In Astronomy 3D or Augmented Reality it is (almost) always "Unknown". While trying setting changing Sensors->Compass->Source to various options, once with Mag+Gyro (Custom) the status became "Good". After changing the option back and forth to see if that was causing the problem, I can't get "Good" again for any option.

Everything seems to be functional in Augmented Reality even with the "Unknown" compass - overlays line up with reality and move correctly,  and I can always switch to the Navigation tool and see a "Good" compass status.

Running Trail Sense 6.0.0 on Android 14 / Kyocera Duraforce Pro 3 phone. The symptom was also present before with Trail Sense 5.10.0 on Android 13.

**Comment by kylecorry31** [comment]
I'll take a look at this tomorrow, I'm able to reproduce this with the options other than Custom it seems.

**Comment by kylecorry31** [comment]
The fix will be in the next release

**Comment by astewart77** [comment]
6.1.0 fix confirmed good for me. Thanks.
