### ISSUE TITLE
Ruler tool helpful additions

### ISSUE THREAD

**Issue by 7eventech77** [kylecorry31/Trail-Sense#2436]
- Ability to toggle ruler numbers direction to reverse. Ex. 0 at top of phone and biggest number at bottom reversing places. This would it easier to read the measurement of objects where the bottom of the phone is touching the object and not having to mentally reverse the numbers. See attached image.
- Ability for ruler to switch sides of the phone using button toggle to switch. This would allow for ruler to be closer to object being measured if it is on right hand side of phone instead of left. See attached image.
![Screenshot_20240616_191035_Trail Sense](https://github.com/kylecorry31/Trail-Sense/assets/142606643/14551de6-718d-4fbf-bbdd-0782b21cdc67)
- Measurement line inside ruler to get precise measurement to have solid color from 0 to highest measurement on line to allow for user to much clearly see where line is. This should switch directions when ruler numbers switch directions. See attached image from different ruler app of what I am referring to.
![Screenshot_20240616_190752_Ruler](https://github.com/kylecorry31/Trail-Sense/assets/142606643/79e661f9-b64e-4d29-98f8-3efa753a5180)

Thank you for any potential consideration!

**Comment by kylecorry31** [comment]
Thank you for the suggestions, I've split this into multiple issues so these features can be tracked separately: 

- https://github.com/kylecorry31/Trail-Sense/issues/2438
- https://github.com/kylecorry31/Trail-Sense/issues/2439
- https://github.com/kylecorry31/Trail-Sense/issues/2440
