### ISSUE TITLE
[Guide] Add more user guides

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#245]
## Navigation 
- [x] Create a beacon
- [x] Navigate to a beacon
- [x] Backtrack (retracing your steps)
- [x] Nearby (see nearby beacons)
- [x] Find a cell phone signal
- [x] Create a beacon from a maps app
- [x] Using a printed map with Trail Sense (ruler, create beacons, plotting your location)
- [x] Determine your location without GPS
- [x] Using the speedometer and odometer to estimate pace and distance travelled
- [ ] Calibrate GPS
- [ ] Calibrate altimeter
- [x] Calibrate speedometer
- [ ] Set navigation quick actions

## Weather
- [x] Getting weather predictions
- [ ] Weather alerts
- [ ] Get distance to a thunderstorm
- [ ] Predicting weather with clouds
- [x] Calibrate barometer
- [x] Calibrate thermometer

## Astronomy
- [ ] Using astronomy information
- [ ] Positioning solar panels

## Tools
- [x] Measuing heights
- [ ] Determing if surfaces are flat
- [ ] Predicting tides
- [x] Evaluating flashlights
- [x] Boiling water
- [ ] Measuring water depth
- [x] Getting help with the whistle and flashlight
- [ ] Getting the current time
- [x] Saving battery
- [ ] Finding dropped metal objects
- [x] Determining avalanche risk
- [ ] Diagnosing sensor issues
- [ ] Determining distance travelled
- [x] Packing for a trip

**Comment by qwerty287** [comment]
I've written a simple guide for the water boil timer (at the first step you could write a little more, but I have no better idea):
```
Boil and purify water

## Boil and purify water so that it is safe to drink it
1. Open the Water Boil Timer
2. Filter the water
3. Bring water to a rolling boil
4. Start the Timer
5. When the timer has expired, enjoy your purified water!
```
(If you know better formulations, feel free to use them and feel free to correct my mistakes.)

And I have a question to the water boil tool, but this isn't the correct issue for this (maybe create another one): Why there's every time this rotating circle when opening the water boil tool? I don't think this tool needs to load much.
![ts](https://user-images.githubusercontent.com/80460567/114386767-f2bd7d80-9b91-11eb-8cfc-8bc87e1d3043.png)

**Comment by kylecorry31** [comment]
@qwerty287 Thanks! As for the loading indicator (I'll include that in the user guide), water boiling times depend on your altitude, so the indicator appears while Trail Sense obtains an altitude reading - though it probably can default to the last known altitude for some time depending on how close you are to the boiling time altitude threshold.

**Comment by kylecorry31** [comment]
Note to put more details into the weather prediction, how the pressure in TS compares to weather stations, and how TS uses pressure data to create predictions.

**Comment by kylecorry31** [comment]
Closing this in favor of #2074
