### ISSUE TITLE
Strange behavior with settings screen

### ISSUE THREAD

**Issue by sm4rk0** [kylecorry31/Trail-Sense#247]
Thank you for this useful app!
There's a bug if you:
1. Enter settings
2. Enter any sub-setting
3. Tap any bottom menu icon
4. Go back with navigation bar

The previous screen from step 3 remains displayed below the settings screen.

Version: 0.9.2 (f-droid)
Phone: Samsung Galaxy S10e
OS: Stock Android 10

**Comment by kylecorry31** [comment]
Hi, 

This was fixed in version 1.0.0 (not yet released) #229 

Thanks for the report!
