### ISSUE TITLE
Lunitidal Intervals

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#2510]
Investigate lunitidal intervals and see if that improves accuracy of the tides tool. If so, add an option to use the calculated lunitidal interval (requires a high tide and a location)

https://www.watchuseek.com/threads/how-to-find-the-lunitidal-interval-for-your-location-knowing-the-times-of-tides.1065973/

https://www.hydro.gov.au/prodserv/data/tides/lunitidal-intervals.htm

https://www.msq.qld.gov.au/tides/lunitidal-intervals

https://www.tidesandcurrents.noaa.gov/glossary.html#lunitidalinterval

https://tidesandcurrents.noaa.gov/publications/Computational_Techniques_for_Tidal_Datums_handbook.pdf  (mentions low and high water intervals - more research needed on that)

**Comment by kylecorry31** [comment]
Initial investigation shows this can improve the tide prediction by just a little bit (on the order of minutes) - but it would be a good step forward to the harmonic tides

**Comment by kylecorry31** [comment]
#2519 will add the ability to use custom times

**Comment by leavenode** [comment]
I see the new option for lunitidal interval, but I can't figure out how to use an already known value to create a new tide chart? It should be as simple as 
'time of high tide' = 'time of the local upper or lower culmination of the moon' + 'local lunitidal interval'
Am I missing something obvious here?

**Comment by kylecorry31** [comment]
Hi, the lunitidal interval that is currently implemented requires you to enter a high tide and it will be automatically estimated. #2519 will add the feature you are looking for.
