### ISSUE TITLE
Solar panel aligner sometimes gives very incorrect azimuth

### ISSUE THREAD

**Issue by Stormwind99** [kylecorry31/Trail-Sense#2562]
Solar panel aligner sometimes gives very incorrect rotation/azimuth - like 90-180 degrees off.

I make sure GPS and Magnetometer are good, and that compass reading makes sense.

If I rotate my phone upside down (giving negative tilt) or if I place the screen against the solar panel (making it hard to see) then it appears the azimuth is correct.

Phone is a Samsung S22+.

![Screenshot_20240918_152628_Trail Sense](https://github.com/user-attachments/assets/08364c8f-e17e-4186-b9b3-9ad086df193c)
![Screenshot_20240918_153252_Trail Sense](https://github.com/user-attachments/assets/eb226f16-0f4c-4959-89c3-a08781b65da6)
![Screenshot_20240918_152642_Trail Sense](https://github.com/user-attachments/assets/ec3b2032-a7f7-487e-b8fd-6f5c1d0ba2cf)
![Screenshot_20240918_152712_Trail Sense](https://github.com/user-attachments/assets/b72ac750-ecb6-42a0-93ba-0cda64f6deff)
![Screenshot_20240918_153121_Trail Sense](https://github.com/user-attachments/assets/011df417-166b-4cbf-bb76-6d949ce57930)
![Screenshot_20240918_153250_Trail Sense](https://github.com/user-attachments/assets/4c44600a-296d-4d0d-bd8c-450bbd9ace8e)

P.S. Thanks for Trail Sense! I use it frequently when camping (full-time now), hiking, and backpacking.

**Comment by kylecorry31** [comment]
Thank you for the detailed report, it definitely seems like the azimuth is incorrect in this case (the target azimuth, not the current device azimuth). I'm able to reproduce the issue on my device as well.

I'll look to fix this in the next release.

**Comment by kylecorry31** [comment]
This should be fixed in the nightly build (https://github.com/kylecorry31/Trail-Sense/discussions/1940). 

The next release will be in early - mid October.

**Comment by Stormwind99** [comment]
Thanks!!!
