### ISSUE TITLE
Offline survival manual Recommended App link broken

### ISSUE THREAD

**Issue by Stormwind99** [kylecorry31/Trail-Sense#2563]
Extremely minor bug: 

User Guide -> Recommended Apps -> Offline survival manual -> Download link leads to missing Google Play Store item "Item not found"

Might be deprecated since I think I read you are working on a built-in survival manual.

**Comment by kylecorry31** [comment]
It looks like it is no longer available on Google Play. I assume because a new release hasn't been published in a long time, it does not meet the Play policy requirements 

I'll see if I can link to the F-Droid version directly.

**Comment by kylecorry31** [comment]
Looks like the only thing preventing the Survival Manual from releasing is broken tests. I'm going to try to fix them.

**Comment by kylecorry31** [comment]
Hopefully this will allow the Survival Manual to be republished on Google Play: https://github.com/ligi/SurvivalManual/pull/290

**Comment by kylecorry31** [comment]
It is back on Google Play and I suspect a new release will happen soon
