### ISSUE TITLE
Moon displays inverted in southern hemisphere

### ISSUE THREAD

**Issue by javimed** [kylecorry31/Trail-Sense#2571]
Moon phases in Trail Sense appear inverted to us southern hemisphere settlers. The upside down moon is explained in this NASA article.

- https://science.nasa.gov/moon/top-moon-questions/#h-are-moon-phases-the-same-everywhere-on-earth

But we don't need NASA. I can share the view of the last quarter moon from my window when I looked up north this morning.

<img src="https://github.com/user-attachments/assets/8c570247-9a0d-4541-a42b-146205408800" alt="Screenshot_20240924_065711_Trail Sense" width="200px">

In the screenshot above, we can see the moon illuminated from the east and the sun arrow pointing where the sun is located in that morning.

But this is not what Trail Sense displays for the AR moon.

<img src="https://github.com/user-attachments/assets/9c923dc9-9dd5-4a66-a7c1-5643dcf75cab" alt="Screenshot_20240924_065738_Trail Sense" width="200px">

In this second screenshot, we can see the moon displayed upside down and illuminated in the opposite side of the sunlight.

It shows inverted in this screen below as well. At least to those of us used to find the moon looking north.

<img src="https://github.com/user-attachments/assets/8ea2fedb-0f5c-4a0a-947c-5828ebbff1a3" alt="Screenshot_20240924_065752_Trail Sense" width="200px">

Correcting the displaying of the moon here would be right too. The graph displays the sun and moon on the same vertical line always and thus there won't be illuminated side issues here tricking the mind.

**Comment by kylecorry31** [comment]
Thank you, I will look to adjust the moon image rotation for latitude
