### ISSUE TITLE
Allow destination bearing while the camera is active

### ISSUE THREAD

**Issue by An-anonymous-coder** [kylecorry31/Trail-Sense#2600]
Hold your phone upright and tap on the compass to activate a destination bearing. This works fine. Now, disable the destination bearing. Tap on the camera icon to turn on the camera. Try tapping the compass to activate the destination bearing. It will not activate. It is possible to activate it before opening the camera and it will stay while the camera is on, but there is no way to activate it after the camera is turned on.

**Comment by kylecorry31** [comment]
Fixed by 82b6f626a6f4e9c96160777973cd44008c7b9479
