### ISSUE TITLE
GPS + Barometer function for Altimeter doesn't fall back to barometer only when GPS is not turned on or is unavailable

### ISSUE THREAD

**Issue by 7eventech77** [kylecorry31/Trail-Sense#2602]
GPS + Barometer function for Altimeter doesn't fall back to barometer only when GPS is not turned on or is unavailable. It stays stuck at the same altitude even though it is changing from what I've noticed but switching it to "Barometer" only fixes the issue; however, this means GPS corrections aren't useable seamlessly.

**Comment by kylecorry31** [comment]
Thank you, I'll look into handling this case.
