### ISSUE TITLE
inclination tab how to

### ISSUE THREAD

**Issue by paulle** [kylecorry31/Trail-Sense#266]
Please can add a short howto for inclination tab.
The bubble and the inclination when you put the phone upright are selfexplaining. But entering values for my height, height and distance for an object, the result is always the same: medium avalanche warning. Even if I use values don't making sense, it's always the same result.

**Comment by kylecorry31** [comment]
Good idea.

For reference, the heights at the top are unrelated to the avalanche warnings - you enter the height and distance, then point your phone to the top of the object (ex. a tree), and when you tap the screen, the height shown should be the height of the object.
