### ISSUE TITLE
Add tool to use device as a heat source

### ISSUE THREAD

**Issue by An-anonymous-coder** [kylecorry31/Trail-Sense#2660]
This is a very risky idea, so I completely understand if it is not implemented. I had the idea for a tool that attempts to heat up the device battery as much as possible, to be used in extreme emergency situations where every bit of heat counts. Obviously this poses the risk of significantly damaging the device, but it is designed for life-or-death situations where it would make sense to sacrifice the device to save a life from freezing. Some things to research would be how effective this heat source would be, the best places to apply the heat source, the fastest way to heat up the device, and if such a tool would break any rules in app stores.

**Comment by kylecorry31** [comment]
Hi, thank you for the suggestion. I have looked into this in the past and decided against it: #356
