### ISSUE TITLE
SOS signal format

### ISSUE THREAD

**Issue by notramo** [kylecorry31/Trail-Sense#288]
From Wikipedia:
> [...] to indicate that the Morse code equivalents for the individual letters of "SOS" are transmitted as an unbroken sequence of three dots / three dashes / three dots, with no spaces between the letters.

The SOS signal shouldn't be as it is currently:
... [space] --- [space] ... [space] ... [space] --- [space] ...
but instead
...---...[space]...---...[space]...---...[space]

**Comment by kylecorry31** [comment]
Hmm, I did not realize that SOS was essentially treated as its own letter in Morse Code - always thought it was three letters. Thank you for pointing this out, I'll fix this for the next release.
