### ISSUE TITLE
Compass sometimes rounds to 360 degrees

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#296]
It should instead display 0 in this case.

**Comment by VarunBatraIT** [comment]
WoW that was quick. I just opened my laptop to convert my email to github issue :P

**Comment by kylecorry31** [comment]
Luckily it was an easy fix - though, I'm going to just bundle it into the next release, as it doesn't really break anything. Thank you for spotting this - it must have been this way for a while
