### ISSUE TITLE
Get Trail Sense "Play Verified"

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#310]
Not exactly sure what the steps are to do so, need to do some research first.

**Comment by qwerty287** [comment]
What does "Play Verified" mean? Does it mean "Verified by Play Protect"? I tihnk, there's no "Play verified", I only know this "Verified by Play Protect". If it'd mean "Verified by Play Protect", you can close the issue. (Trail Sense is already verified by Play Protect.)

**Comment by kylecorry31** [comment]
Okay, thanks! Someone left that in a review on the Google Play store, and it showed as verified by play protect for me (seemed it did that by default, but I didn't have another device to check with) - I created this to look into if there was anything else I needed to do (as I didn't find anything with a quick google search).
