### ISSUE TITLE
Add clock sync notification

### ISSUE THREAD

**Issue by aw-bib** [kylecorry31/Trail-Sense#323]
- I understand the GPS clock displays the phones time, at least if no GPS signal is available. Maybe, an indicator would be in order here?
- It would be nice if it could give a [time signal](https://en.wikipedia.org/wiki/Greenwich_Time_Signal) so you could easily adjust an external watch (wrist watch or the like). Handy, especially as the GPS time signal would probably be the most precise to get. I'd suggest a small button (or press the clock) to enable the pips for the next full minute.
- Would the GPS clock actually _adujst_ the phones clock?
- One may consider to give the clock a place in the main icons (e.g. prev/next to astronomy) and to integrate tools that essentially rely on time (cliff height, lightning strike distance, water boiler).

isRelatedTo: #306

**Comment by kylecorry31** [comment]
@aw-bib depending on how quickly your GPS gets a fix, it does display some text to the bottom of the screen to let you know it's updating it from GPS. 

I'll consider making something like that, even if it's just a notification. That would help if your the Android settings page as well.

I don't think Trail Sense can update the time without elevated privileges, but on some phones if you have time set to automatic, the GPS might update the time - probably depends on the manufacturer though. 

The only problem with putting it on the bottom bar is that there is a limit of five icons there. I do plan on organizing the tools page soon into sections.
