### ISSUE TITLE
Onboarding screen overlap when font accessibility settings enabled

### ISSUE THREAD

**Issue by franklinbill** [kylecorry31/Trail-Sense#338]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the icon and the following text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display. I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 1.4.1, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
<img width="472" alt="bug-trail_sense" src="https://user-images.githubusercontent.com/18572115/103221174-fa4b7480-495c-11eb-99c6-363889c78ef7.png">

**Comment by kylecorry31** [comment]
Thank you for the report, I'll adjust this screen accordingly - as well as see if any other screens are affected.

**Comment by franklinbill** [comment]
Thanks*100000 for your reply!
