### ISSUE TITLE
Widgets (quick action and homescreen)

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#347]
Both in app and homescreen widgets. 

Note: Homescreen widgets may have some features disabled as there are limits imposed by Android.

- [x] Quick action to open widgets panel
- [x] Support for half width widgets
- [x] Add widgets to tool registry
- [x] Add homescreen widget support
- [x] Create widget update worker
- [x] Add widget previews and label
- [x] Properly set minimum widget size
- [x] Disable homescreen widgets if tool is unavailable
- [x] Detect if the widget is running in app or on a homescreen
- [x] Let user choose which widgets to show (in app)
- [x] Link broadcasts to widget in tool registry
- [x] Trigger a widget refresh
- [x] Current weather
- [x] Sunrise / set
- [x] Moon
- [x] Current tide
- [x] Nearby beacons (list)
- [x] Elevation
- [x] Pressure chart
- [x] Sun/moon chart
- [x] Tide chart
- [x] Location
- [x] Pedometer (steps + distance)
- [x] Backtrack
- [x] Pressure + tendency
- [x] Flashlight (basically the quick action, but the entire widget is clickable)
- [x] Move widget helpers to andromeda
- [x] Add to user guide

Additional widgets were moved into a separate issue.

**Comment by kylecorry31** [comment]
(quick actions to the tools)

**Comment by aw-bib** [comment]
Random idea: if their content is dynamic they'd also add an informative aspect. E.g. a small barograph leads to weather, moon phase (probably with the next raise/set event) to astronomy.

**Comment by kylecorry31** [comment]
Closing this in favor of https://github.com/kylecorry31/Trail-Sense/issues/2415 which contains both in app and homescreen widgets (ended up being really easy to create widgets).

**Comment by kylecorry31** [comment]
![PXL_20241110_005412325](https://github.com/user-attachments/assets/b695abf8-29fd-4700-b77b-d2d1d824b2b2)

**Comment by michaelblyons** [comment]
That is many widgets.

**Comment by kylecorry31** [comment]
> That is many widgets.

This is only about half of them :)

The rest can be found here: https://github.com/kylecorry31/Trail-Sense/issues/2686

My goal is to let users create a full custom Trail Sense dashboard on their homescreen with the information they care about (rather than me choosing what that information is).

Here's my homescreen dashboard for reference (and I have a couple widgets on the first page of my homescreen - sun and flashlight):
![Screenshot_20241123-130554](https://github.com/user-attachments/assets/febdd6da-bafc-477e-bec1-6a68743d062e)
