### ISSUE TITLE
Add daily weather outlook

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#397]
A notification every morning that uses longer-term changes in pressure (24 or 48 hours) to determine what the weather will likely be compared to yesterday (ex. worse than yesterday, better than yesterday, about the same as yesterday). Corresponds to the daily weather trend on the weather page (which only appears when a change is expected)

**Comment by aw-bib** [comment]
There was an idea on this line in #179 constructing a tangent at a given point to get a clear tendency reading.

Allowing this "tangent" to be constructed between two points that are _t_ (say t=3h 6h 12h 24h 48h) apart might be an interesting idea. Probably, giving a better "feeling" on what's going on than a number.

**Comment by kylecorry31** [comment]
So the daily outlook that's currently on the weather tab uses the linear regression (slope) of the 48 hours to generate its prediction, I plan to use something similar here - it is very similar to the tangent idea
