### ISSUE TITLE
ruler shows lines with 1.25mm distance

### ISSUE THREAD

**Issue by JensKorte** [kylecorry31/Trail-Sense#424]
The ruler shows me lines with a distance of 1.25mm. That is quite unusual for Germany. The version used is1.5.3 from F-Droid. My phone is a Galaxy S5 with a recent LineageOS.

It would be nice, if the lines would have 1mm distance or there should be at least a legend telling the distance is 1.25mm.

Thanks for the nice programm

![Trail_Sense-ruler](https://user-images.githubusercontent.com/2682123/106571199-26977980-6537-11eb-8b00-b7975c7e38bd.png)

**Comment by kylecorry31** [comment]
Thanks! I will fix this in the next release (1.7.0)
