### ISSUE TITLE
Invalid location error when converting from UTM

### ISSUE THREAD

**Issue by ZweiAmTag** [kylecorry31/Trail-Sense#425]
As the title says, conversion from UTM to any other format is not possible.
From decimal to UTM | From UTM to decimal
-----------------------|-----------------------
![From decimal to UTM](https://user-images.githubusercontent.com/30526171/106782635-af530a00-664a-11eb-8b25-8554bc32c1ec.png) | ![From UTM to decimal](https://user-images.githubusercontent.com/30526171/106782653-b417be00-664a-11eb-8bca-e1781d275ae5.png)

**Comment by kylecorry31** [comment]
Hmm, that works fine for me. Could you copy and paste the text you entered into this issue? I'm wondering if there's some sort of encoding issue with the characters.
![Screenshot_20210203-125328](https://user-images.githubusercontent.com/5938560/106788440-f2978380-661e-11eb-985b-6caec0e3c21b.png)

**Comment by kylecorry31** [comment]
And what version of Trail Sense are you using?

**Comment by ZweiAmTag** [comment]
I'm using Version 1.6.0.
This is the input: 32T 0425513E 5302733N
Setting the format to UTM in settings and taping the satellite icon next to the input field , so that it inserts the current location in UTM, gives the same error message.

**Comment by kylecorry31** [comment]
Thank you, that is really weird, it works when the device language is English, but not German. I'll investigate further and hopefully provide a fix with the upcoming release.

**Comment by kylecorry31** [comment]
Fixed in 1.7.0 (releasing over the weekend most likely)
