### ISSUE TITLE
[Altimeter] Add NMEA MSL altitude support

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#429]
Some devices may return the MSL altitude directly from the NMEA GPS API, this can be parsed to get an accurate altitude without the use of the geoids

https://stackoverflow.com/questions/9361870/android-how-to-get-accurate-altitude

**Comment by gdt** [comment]
Also, note that the NMEA stream contains an approximation to the geoid offset in addition to giving "WGS84 altitude".   However, I have seen in many receivers that the built-in geoid model is poorer than what one would expect.   For some locations in New England, the device-reported value seems as much as 4m different from the EGM2008 value.
