### ISSUE TITLE
Add tilt, incline

### ISSUE THREAD

**Issue by Ygarr** [kylecorry31/Trail-Sense#438]
Please add angle level meter, angle of slope

**Comment by Ygarr** [comment]
![Uploading Screenshot_20210212_152937_com.huawei.compass.jpg…]()

**Comment by Ygarr** [comment]
![Screenshot_20210212_153022_com huawei compass](https://user-images.githubusercontent.com/14309871/107774846-39385c80-6d48-11eb-8a88-a4408bd09486.jpg)
![Screenshot_20210212_152937_com huawei compass](https://user-images.githubusercontent.com/14309871/107774851-3c334d00-6d48-11eb-9ed4-7939037dba88.jpg)

**Comment by kylecorry31** [comment]
@Ygarr  Hello, this tool already exists, you are looking for the Inclinometer (under the tools tab), or the bubble level

(inclinometer is designed for slope/height measurement while the bubble level is meant to tell if a surface is flat)
