### ISSUE TITLE
[Distance Convert] Distance converter swap

### ISSUE THREAD

**Issue by JonnyTech** [kylecorry31/Trail-Sense#439]
Is it possible to quickly swap distance converter units, ie from feet/meters to meters/feet? A swap/invert button rather than having to fiddle with dropdowns would be helpful.

**Comment by kylecorry31** [comment]
Good idea!

**Comment by qwerty287** [comment]
I just implemented this feature - to which branch should I create a pull request?

**Comment by kylecorry31** [comment]
You can do it to main, if it's a small change I'll push it through, if not I'll hold off until 2.1.0 is released. Thanks!
