### ISSUE TITLE
[Whistle] Add international whistle codes

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#443]
Where are you? : 1
Acknowledged: 1
Come here: 2
Help: 3

**Comment by qwerty287** [comment]
Is it okay if I implement this? If yes, I would need some more information, especially how the UI should look.

**Comment by kylecorry31** [comment]
Unfortunately that's all the info I have here, I'm not even sure if it should be implemented or should just be a user guide. (This was a community suggestion)

As for UI, I haven't been able to find a nice way of doing this, so I'm not sure - maybe a popup when you long press the "help" button for now? That wouldn't be too discoverable, but then again I'm not sure how useful this feature would be - most people only know the help signal

**Comment by qwerty287** [comment]
You could create a new "screen" (fragment) for this and a link to the on the main whistle fragment (instead of the "help" button)

**Comment by kylecorry31** [comment]
I'm not sure if I like that approach, I would either prefer a popup where the user selects the whistle (to see what it looks like/how it works, still unsure if I want to have this feature) or not have this feature.

**Comment by qwerty287** [comment]
OK, I'll see if this is useful (the UI idea).

**Comment by qwerty287** [comment]
Ok I implemented this, see the GIF below. ("Trillerpfeife" is whistle in German, "Hilfe" is help in German) 
![ts](https://user-images.githubusercontent.com/80460567/116037464-6cf90200-a668-11eb-81d7-795be56e3857.gif)

I think, the user experience isn't the best, but it's okay.

**Comment by kylecorry31** [comment]
That looks good, as mentioned I don't think most people know those codes so I'm find with the usability there. I'm still debating whether it's worth adding it though. And given that pressing help is designed to repeat over and over (the thought was that you could set your device down while it played - expanded by #561 ) - I would be worried that all of the codes would be interpreted as help anyway. The more I think about it, the more I believe it just belongs in the user guide. Feel free to submit the PR, and if I decide it's worth adding this, then I'll merge it in.
