### ISSUE TITLE
Broke GPS status and beacon button on 1.7.1

### ISSUE THREAD

**Issue by XPXPv2** [kylecorry31/Trail-Sense#448]
The GPS status and beacon button position jump up and down rapidly and slowly drift up and off the screen after updating to 1.7.1
![Screenshot_20210225-210734-323](https://user-images.githubusercontent.com/49757854/109246307-006c9e80-77b0-11eb-9cd0-7efd3adadedd.png)

**Comment by kylecorry31** [comment]
Hi this was fixed in 1.7.2. I don't think F-Droid published it yet though, I opened an issue there because it looks like they are still having metadata issues.

A quick fix for now would be to install from Google Play or calibrate your compass (rotate in a figure 8)
