### ISSUE TITLE
Clock jumps to wrong time

### ISSUE THREAD

**Issue by aw-bib** [kylecorry31/Trail-Sense#455]
If I open the clock app, the system clock is displayed. Once I switch on the GPS, I get a notification `Updating time from GPS...` If I do have a stable GPS _everything is fine_.

However, if I happen to be in a room and the phone is still searching for satellites (and most likely will never get a signal) at some point I get a time out. The message changes to the `[Update system time]` button _and_ the clock actually jumps to some _random_ time. Best guess: it takes the time it got during the last satellite reception. E.g. right now even the date jumped a day back. (I am pretty sure though that I did not have a satellite signal a 0533 in the morning, so the time is somewhat unclear.) I guess this is a side effect related to #307

I think, one should notify the user if  a time reception was not possible, but then display the phones time instead. It is a nice feature that with the GPS time signal we can get one of the most precise clocks, indeed. (And IMHO it looks great as well ;)

If I switch the GPS receiver _off_ and start the clock everything is fine as TS doesn't try to sync in the first place. (It might be a good idea to give a hint that the system time is used here, like in the case we don't get a GPS fix in time.)

Trail Sense 1.7.2 (F-Droid)

**Comment by kylecorry31** [comment]
You are 100% right, I'll fix this - thanks!

**Comment by kylecorry31** [comment]
This will be fixed in 1.9.0
