### ISSUE TITLE
[Flashlight] Red screen light

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#483]
Related to #472

**Comment by qwerty287** [comment]
Does "red screen light" only mean to turn the screen red (when using the screen flashlight)?

**Comment by kylecorry31** [comment]
Yes, I was thinking there would be a little colored box in the top right corner that if the user clicked it, the screen would become red (and the box would then turn white, so the user could click that and it would turn white again, and repeat)

**Comment by qwerty287** [comment]
I think, that's an easy task, so I'll implement it.

**Comment by kylecorry31** [comment]
Awesome, thanks! Feel free to do the PR directly to main, I'll include it in the 2.1.0 release (I'm not releasing until probably next weekend, I'll probably be done with the rest of the 2.1.0 features this weekend, but have a bunch of testing to do)
