### ISSUE TITLE
Create speedometer view

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#501]
A dial view for the speedometer tool

Kind of like this in terms of minimalism: https://ae01.alicdn.com/kf/H6eee9b9577394a58a2e1107c7998ae9b2.jpg_q50.jpg
With the instantaneous speed in the center, and nothing on the bottom where the odometer is in the photo. This will replace the instantaneous speed textview in the UI, the other views will appear below it.

But with the minute hand of the Clock (make it colorPrimary).

If speed is greater than 4.5 m/s show this:
The min speed is 0, and the max speed can be 100 mph or 160 km/h (intervals of 20, evenly spaced - that would mean a different number of lines for mph and km/h)

Else show this:
The min speed is 0, and the max speed can be 10 mph or 16 km/h (intervals of 2, evenly spaced - that would mean a different number of lines for mph and km/h)

The hand should point to the current speed on the speedometer

**Comment by qwerty287** [comment]
I'm trying to implement this now, but should the average speed text view inside of the dial view (like the instantaneous speed) or outside?

**Comment by kylecorry31** [comment]
Outside (below where it is currently) - this is only for the instantaneous speed

**Comment by kylecorry31** [comment]
A dedicated speedometer does not fit into TS' use cases, so new dial is needed. The speed will be kept on the navigation tab and average speeds may be shown on the odometer tool.
