### ISSUE TITLE
Open corresponding tool from notifications

### ISSUE THREAD

**Issue by qwerty287** [kylecorry31/Trail-Sense#518]
Hello,
there are two small things with the notifications that could be improved:
1. when you tap on the water boil timer notification, nothing happens. It should open the water boil tool.
2. when you use the flashlight and turn it off, the notification stays for a few seconds. It would be good if it disappears immediately after turning off the flashlight.
(I can also open individual issues if that is better).

**Comment by kylecorry31** [comment]
Thanks, I created this issue: https://github.com/kylecorry31/Trail-Sense/issues/520 to track the notifications not dismissing instantly (I think it is an operating system thing, but I will explore more).

Other areas where the notifications should open the corresponding tool:
- Odometer
- Clock
