### ISSUE TITLE
Location permissions can be optional 

### ISSUE THREAD

**Issue by dennisguse** [kylecorry31/Trail-Sense#52]
Compass and barometer do not require the location permission.
So, location permission should be made optional if the user needs the beacon feature.

**Comment by kylecorry31** [comment]
Good point, thanks!

**Comment by kylecorry31** [comment]
FYI, I committed this to master. Denying the location permission will have the following side effects

- The weather feature will still work, but you will not be able to convert it to sea level pressure (which will make the forecasts less accurate while moving between elevations). 
- Beacons are disabled
- The location displayed (if any) on the navigation screen will be the last location you were when Trail Sense had location permissions
- The astronomy tab may be inaccurate (same as above point with cached location)
- True North will not work
- Altimeter may be inaccurate (only uses barometer)

I didn't disable any of the settings when the permission is denied - that is a low priority, so I may revisit it later.

**Comment by kylecorry31** [comment]
I should also mention that some of those issues can be remedied once I implement the manual calibration feature.
