### ISSUE TITLE
Foreground notifications don't go away instantly

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#520]
I'm not sure if this is fixable, I notice this happens with other apps and canceling the notification after the service is stopped doesn't instantly remove it, so it may be something with the OS

https://github.com/kylecorry31/Trail-Sense/issues/518

**Comment by kylecorry31** [comment]
This appears to be intended system-level behavior: https://issuetracker.google.com/issues/147792378

https://stackoverflow.com/questions/59526254/foreground-service-notification-always-shown-for-at-least-5-seconds

I don't agree with it, but it's what we got.

"[foreground] notifications must be visible for at least 5 seconds"

I guess that is to prevent apps from quickly doing stuff without the user noticing because they rapidly cancel their notification.

**Comment by qwerty287** [comment]
Maybe you could add this to an user guide.

**Comment by kylecorry31** [comment]
I can add that to the FAQ, but I don't think it belongs in the user guide
