### ISSUE TITLE
Import a map with the camera

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#525]

**Comment by kylecorry31** [comment]
Taking a photo with the camera requires and external storage permission, and I don't want that (to get the full sized bitmap). Until I find an alternative, this is on hold.

**Comment by kylecorry31** [comment]
If the camera features are on, this can be done directly from TS.

**Comment by Lee-Carre** [comment]
You might take some inspiration from [MapEver](http://www.github.com/diedricm/MapEver); an older app which tackles the same idea.

**Comment by kylecorry31** [comment]
@Lee-Carre that's really cool - I didn't think there were other apps that did this! Looking at the code, I can see that they used a more complex algorithm than I did, it might be worth seeing why / if an approach like that would be beneficial here.

(unfortunately, it doesn't seem to work on Android 12 anymore - I'll have to give it a try on an emulator)
