### ISSUE TITLE
Add geospatial PDF support

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#534]
Auto calibrates the map

**Comment by eresonance** [comment]
You should advertise this feature! Most people who want this kind of support are using Avenza maps, nice to see TS has this support too.

**Comment by kylecorry31** [comment]
Thanks! There are a few performance issues and features I want to implement in maps first, but once that is done, I'll move it out of experimental mode and advertise it (my goal is by the middle of this year).
