### ISSUE TITLE
Navigate with a path

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#535]
You can navigate with a path on the radar compass or map, and select them from a new tab on the beacon screen. They can only be imported from a GPX file.

Navigation to a path will just show the path and your current position (and the backtrack history)

**Comment by kylecorry31** [comment]
Navigating to a track when nearby/radar is disabled will switch to the radar compass

**Comment by qwerty287** [comment]
TS should send a notification or inform you if you leave the track.

**Comment by kylecorry31** [comment]
![PXL_20210414_005955261](https://user-images.githubusercontent.com/5938560/115118557-c5961400-9f71-11eb-9fdb-15ba0d09b3ae.jpg)

**Comment by kylecorry31** [comment]
Closing this as you can display paths on the radar compass and map in 3.0.0
