### ISSUE TITLE
How to quit Trail-Sense?

### ISSUE THREAD

**Issue by dennisguse** [kylecorry31/Trail-Sense#54]
I could not figure how to close trail-sense (also remove notification).
Did I miss something?

**Comment by kylecorry31** [comment]
Hi,

Trail Sense will run in the background to monitor the weather (if it doesn't do that, it won't be able to give you weather forecasts or show the barometer history). Android requires that a notification is present for apps that run in the background like this - I can research this further, but I expect I won't find much of a solution here. 

What I did on my phone, was set the "Weather" notification category for Trail Sense to Silent and Minimize within Android's settings.

Would you expect to be able to opt-out of the weather monitoring feature? If so, I can add a setting for that.

**Comment by dennisguse** [comment]
@kylecorry31 No, I meant that I want to shutdown the weather monitoring if I don't need it.
Like in home office ;)

**Comment by kylecorry31** [comment]
Okay, I think I am going to create a setting for this to turn on / off the weather monitoring and allow it to be turned off via the notification. How does that sound?

Thanks for the feedback!

**Comment by kylecorry31** [comment]
![Screenshot_1589486038](https://user-images.githubusercontent.com/5938560/81979592-395dcd00-95fb-11ea-8849-04825e4290ba.png)

**Comment by kylecorry31** [comment]
Or would you expect that after stopping the monitoring, you would need to take another action within Trail Sense to restart it, rather than just opening the app?

**Comment by dennisguse** [comment]
Sounds like a great idea.
I like it :)
