### ISSUE TITLE
water boil timer ignores the "cancel" button if you leave the app and open it again

### ISSUE THREAD

**Issue by qwerty287** [kylecorry31/Trail-Sense#553]
The title should say it, but see the video below. It's an AVD, so it's very slow.

https://user-images.githubusercontent.com/80460567/114423313-5b6b2100-9bb7-11eb-8788-69056ca6a224.mp4

**Comment by kylecorry31** [comment]
The cancel button in the notification seems to be doing some odd behavior as well (still clickable, but it enables and disables every second)

**Comment by kylecorry31** [comment]
Fix is in main
