### ISSUE TITLE
Print a map

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#575]
- [x] Print map from list
- [x] Print map from map

**Comment by kylecorry31** [comment]
If this requires Internet, then I won't do this - but if it goes through the Android system, then it is fine.

**Comment by kylecorry31** [comment]
If I can't do the printing, then allow sharing the map as an image.

**Comment by qwerty287** [comment]
I could do this - is this ok? (From what I know, this doesn't require internet access)

**Comment by kylecorry31** [comment]
I would say hold off on this for now - the map tool is under active development and there are many moving parts. I'll let you know when it is more stable though
