### ISSUE TITLE
Toggle sunrise/sunset theme on resume

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#590]
Right now it works on create, but it might be useful if TS was in the background and reopened later in the day. This should only be done if it doesn't affect performance / is buggy or is annoying to users. 

Only when the sunrise/sunset theme is enabled.

**Comment by qwerty287** [comment]
I tried to implement this, but I think (in the way I implemented it) it could be annoying. See the GIF below.
![ts](https://user-images.githubusercontent.com/80460567/115266763-c5944080-a138-11eb-8549-a028e37e7d33.gif)

**Comment by kylecorry31** [comment]
Yeah, that wouldn't be a fun user experience

**Comment by kylecorry31** [comment]
Yeah, I think the only way is to recreate the activity, which isn't always desirable. Once Jetpack Compose has a stable release, I'm going to switch over to it, at which point this should be feasible.

**Comment by kylecorry31** [comment]
I'm going to close this in favor of using the system options for day/night theme. I don't think I'm going to switch Trail Sense to Jetpack Compose - too much work for that.
