### ISSUE TITLE
Determine stride length from GPS

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#635]
1. User says they want to calculate stride length
2. Prompt to start walking
3. GPS tracks distance until an accurate value is determined for stride length or the user stops it

- [x] Create stride length calculator
- [x] Create screen for stride length estimation
- [x] Let the user save estimated stride length
- [x] Open the stride length estimation screen from pedometer settings

**Comment by Lee-Carre** [comment]
> GPS tracks distance until an accurate value is determined for stride length or the user stops it

What about continual auto-calibration in the background (much like for barometer-based altitude from GNSS)?

* Stride-length may change over the journey (depending on terrain, conditions, footwear).
* Adapts to whoever happens to be carrying the device (imagine a communal backpack being passed around, to share the load, during a trek).

In such a case, it may be helpful to have a method for triggering a calibration reset.

**Comment by kylecorry31** [comment]
@Lee-Carre good idea - I created a new issue for that https://github.com/kylecorry31/Trail-Sense/issues/1164
