### ISSUE TITLE
Remove AMSL setting

### ISSUE THREAD

**Issue by gdt** [kylecorry31/Trail-Sense#641]
The altimeter settings tab has "Use AMSL altitude" and this is quite reasonably default-checked.   The subtext of "Correct GPS alttitude" however is misleading.   GPS intrinsically measures ellipsoidal height (HAE), and that isn't wrong -- it's just not of interest to normal people.   The process of converting "WGS84 Height Above Ellipsoid" to "WGS84 orthometric height" by applying EGM2008 (or a coarser/earlier approximation).

So I would change the subtext to

Display height above sea level (rather than ellipsoidal height).

Alternatively, and this is my real suggestion  -- just delete the preference  and do not provide a way to show HAE.  HAE has really nothing to do with trails/etc.

**Comment by kylecorry31** [comment]
I agree, I'm going to go with your real suggestion and delete that. That setting was added back when I wasn't sure if that was the correct thing to do and I never removed it. I think the real setting here is the geoid source (the one packaged with Trail Sense or NMEA)
