### ISSUE TITLE
Research raw GNSS measurements

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#645]
I'm not really expecting this to go anywhere, but I'm interested to see what's available and if that could be used in any way.

**Comment by JensKorte** [comment]
https://en.wikipedia.org/wiki/GNSS_reflectometry
I am unsure if this is of any use. In the [german WP article](https://de.wikipedia.org/wiki/GNSS-R) it sounds like: if a satellite is just above the horizon, it can be used by a GPS receiver to measure the reflections on the surface of the water and tell something about the waves.

**Comment by kylecorry31** [comment]
Unfortunately, it doesn't look like there is anything I can get out of the GNSS API that would be useful which the location API doesn't provide.
