### ISSUE TITLE
Add linear compass display when phone is vertical

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#65]
Like Skyrim / Subnautica / battle royale games

**Comment by kylecorry31** [comment]
Beacons shown offscreen will need to have an arrow pointing toward them until they are shown on screen

**Comment by swedneck** [comment]
It'd be nice to show the direction to beacons on the normal compass as well, should that be a separate issue?

**Comment by kylecorry31** [comment]
I had meant the active beacon, which is currently present on the current compass mode. You are referring to displaying all beacons correct?

**Comment by swedneck** [comment]
Ah, well maybe the user could select a number of beacons to display?

**Comment by kylecorry31** [comment]
Okay, I like that. So the user would be able to show the closest X beacons (unless a beacon is being navigated to, I believe). I don't want to the UI to be too cluttered so I will explore a few different designs for this.

**Comment by kylecorry31** [comment]
Here's the progress on this so far:

![Screenshot_1589830199](https://user-images.githubusercontent.com/5938560/82252174-82c05c00-991c-11ea-952d-d69f2b94769b.png)

**Comment by kylecorry31** [comment]
Note to self: customize the linear compass library to match the ticks with the round compass / adjust the UI a bit
