### ISSUE TITLE
Add multiple share sheet options

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#67]
Like that present in OsmAnd~

**Comment by dennisguse** [comment]
You mean an IntentChooser?

**Comment by kylecorry31** [comment]
Not exactly, more like this:

![Screenshot_20200519-094106](https://user-images.githubusercontent.com/5938560/82333596-eeee9e80-99b4-11ea-9359-729ec26ce9ae.png)
