### ISSUE TITLE
Make Trail Sense a share target for images / PDFs

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#678]
This would open the map import screen.

**Comment by qwerty287** [comment]
I could do that, is that ok?

**Comment by kylecorry31** [comment]
Yes, but be aware that this needs to respect the experimental feature setting for maps (i.e. no share target while the experimental setting is off) - if that's possible, then it should be alright to implement this.

And note, I don't want TS to have the write/read external files permission - so if the images can't be imported this way without it then this issue can be closed
