### ISSUE TITLE
Motion alarm

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#679]
Set alarm and leave phone in a bag overnight, if the bag is moved the alarm will sound (could be good bear deterrent as well to scare them if they mess with your bag)

- Explore significant motion sensor, accelerometer

**Comment by aw-bib** [comment]
Maybe GPS coordinate leaves circle of ... around current position is an idea here as well.

**Comment by kylecorry31** [comment]
After further consideration, I will not be adding this.

Reasons
- Limited use cases / frequency
- High battery usage potential
