### ISSUE TITLE
'Sunrise/Sunset (Astronomical)': should read 'Dawn/Dusk (Astronomical)'?

### ISSUE THREAD

**Issue by jer194** [kylecorry31/Trail-Sense#684]
I'm not sure about Englisch, but at least in German all the dawns and dusks are named similar, eg:
Buergerliche Daemmerung
Nautische Daemmerung
Astronomische Daemmerung

Isn't it the same in English?
TS says 'Sunrise (astronimcal)', shouldn't it read something like 'Dawn (astronomical)'?

At least if I read 'Sunrise' or 'Sunset', I expect the sun to appear / disappear ...

**Comment by kylecorry31** [comment]
You are correct, I'll change that wording
