### ISSUE TITLE
Open TS on long press of tile

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#687]

**Comment by qwerty287** [comment]
(Or corresponding tool would be even nicer, weather monitor -> weather page, flashlight -> flashlight tool, backtrack -> backtrack tool)

**Comment by qwerty287** [comment]
I just experimented with this, and I'm not sure if you can open the corresponding tool. If the app is opened from a tile, it has an intent, but these intents are the same if you press on the weather monitor tile or the pedometer tile or the backtrack tile...

**Comment by qwerty287** [comment]
I could create a pull request that opens the app on long press, should I do this?

**Comment by kylecorry31** [comment]
Sure, that is fine for this issue - it should just open the MainActivity
