### ISSUE TITLE
Hide weather monitor tile if no barometer

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#688]

**Comment by qwerty287** [comment]
The same for the flashlight? Phones usually have a flashlight, but maybe you use the app on a tablet. (It's the same for the flashlight settings, but that should be another issue)

**Comment by kylecorry31** [comment]
There is no flashlight tile from Trail Sense - I only made the ones for settings/background services

**Comment by kylecorry31** [comment]
(created a separate issue to track the flashlight settings)

**Comment by qwerty287** [comment]
Yeah, thanks, I just realized that there's no flashlight tile, sorry ;)
