### ISSUE TITLE
Feature: Hand warmer mode

### ISSUE THREAD

**Issue by ChildishGiant** [kylecorry31/Trail-Sense#690]
I remember seeing one back when I had an iPod touch. I imagine it just works the CPU very hard to achieve this. Can't be good for the CPU but could be useful. A warning about harming your phone would probably need including.

**Comment by kylecorry31** [comment]
I explored this in #356 and didn't have luck - the phone doesn't really get hot enough / doesn't transfer heat well enough for this to be useful unfortunately
