### ISSUE TITLE
Wrong white noise notification

### ISSUE THREAD

**Issue by Flbk** [kylecorry31/Trail-Sense#692]
Trail sense 2.1.3

I don't know if it is related to the French translation but the text on the remaining notification when the white noise is activated says "Press to turn off the flashlight".

![Screenshot_20210521-204232](https://user-images.githubusercontent.com/72269109/119185119-aa3d8d80-ba76-11eb-94f0-4e8625018182.png)

Anyway just a little bug, this app is amazing.

**Comment by kylecorry31** [comment]
Thanks, I'll clear that translation to show it needs to be updated
