### ISSUE TITLE
[Bug] Incorrect backstack for navigation long press

### ISSUE THREAD

**Issue by qwerty287** [kylecorry31/Trail-Sense#702]
I don't know how I should describe my bug better than with the repro steps:
1. Long click on the beacon button on navigation tab to create a beacon
2. Create and save the beacon
3. You are being redirected to the beacon select screen
4. Use androids back button to go back
5. You'll be redirected to the beacon create screen with the values filled in that were used for the beacon creation in the first step

**Comment by kylecorry31** [comment]
There's a similar problem with the create beacon from geo function as well
