### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#72]
This tool may be helpful: https://developer.android.com/studio/write/translations-editor

Please fork this repo and submit a pull request with the translations, thank you!

**Comment by pr0gr8mm3r** [comment]
Sine version 0.3.0 the app's name has been translated (for German at least) by @paulle in Pull request #83 or somewhere prior. This made me wonder if fhe app name should even be translated, as the English name sounds way more modern to me. However, I can also understand if people want it to be in their language, I just think there should be guidance added on this topic in the Contributing section of the Readme so it can be done in the same way for all languages.

**Comment by paulle** [comment]
I believe the app name shouldn't be translated. It's OK with an app name in English. Depending of language the app name can become much larger.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 27. Mai 2020, 14:12, p_0g_8mm3_ schrieb:
