### ISSUE TITLE
Feature request: Heart rate montior

### ISSUE THREAD

**Issue by ChildishGiant** [kylecorry31/Trail-Sense#728]
I've seen many apps where you cover your camera with your finger and it claims to give a rough bpm. I was wondering if this would be a good addition to the app

**Comment by kylecorry31** [comment]
@ChildishGiant Hi, I considered this in issue #369 and decided against it (reasoning in that issue). I'm also still unsure if I'm going to publish Health Sense - I don't really want to get into medical-related stuff (at least in a publically release app).

**Comment by ChildishGiant** [comment]
Sorry for the duplicate, i searched but didn't find anything. Thanks for the response 😀
