### ISSUE TITLE
Quick find next astronomy event

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#739]
- Full moon
- New moon
- First Quarter
- Last Quarter
- Meteor shower
- Eclipse (when implemented)

Finds the next occurrence of the event from the display date (exclusive) and sets the date to that.

This can be accessed by clicking the date picker on the astronomy tab - appears above the calendar view as a dropdown and search button.

**Comment by aw-bib** [comment]
May I suggest the moons quarters? (Relevant for neaps vs. springs.)
