### ISSUE TITLE
Testing Trail Sense Debug Builds

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#74]
You can get debug builds for Trail Sense here: https://www.dropbox.com/sh/gplqslml3iyq2ec/AACn0Arv3KRHAUF1wCusmoZ2a?dl=0

I'll post a new comment here each time I build a debug build so you can download it and provide feedback on some new features while they are still in development. 

If you are interested in getting a debug build, please leave a comment on this issue and I will create a new version and say what's in it. I stopped generating them automatically due to lack of feedback/engagement.

**Comment by sethtara** [comment]
![Screenshot_20200520-163230](https://user-images.githubusercontent.com/48066700/82439413-3f9af000-9ab8-11ea-84f3-76628bf65e29.png)

### Little UI changes required

**Comment by sethtara** [comment]
![Screenshot_20200520-163343](https://user-images.githubusercontent.com/48066700/82439573-87ba1280-9ab8-11ea-871f-90f846390dd5.png)

#### having  ruler at side is nice but having it by default at first glance doesn't look that great..

**Comment by kylecorry31** [comment]
@sethtara Thanks! I totally agree with that, I was thinking of adding a button to slide out the ruler and putting a background on it so it doesn't mess with the linear compass. In the meantime, I added a setting to show/hide the ruler.

**Comment by sethtara** [comment]
![Screenshot_20200520-164154~2](https://user-images.githubusercontent.com/48066700/82440119-758ca400-9ab9-11ea-89ee-fcc83fbb76ae.png)

#### How about adding the language option a start..

**Comment by sethtara** [comment]
![Screenshot_20200520-164916~2](https://user-images.githubusercontent.com/48066700/82441602-cac9b500-9abb-11ea-8d04-700ad283ad6e.png)


### some UI tweaks needed


### I tried to fix it 
![Screenshot_20200520-165935~2](https://user-images.githubusercontent.com/48066700/82441682-eb920a80-9abb-11ea-95a7-29c1874e9d24.png)

**Comment by kylecorry31** [comment]
A new version has been uploaded containing a version of the astronomy fix

**Comment by kylecorry31** [comment]
A new version has been uploaded containing translations and the ability to turn off weather monitoring in the background via settings.

**Comment by kylecorry31** [comment]
A new version has been uploaded. Contains setting (off by default) to display multiple beacons (WIP, see that issue for more details) - early feedback welcome!

It also contains a ruler scaling factor setting that may be needed for some devices.

**Comment by kylecorry31** [comment]
#### New debug build
- Beacons can be marked as visible
- Setting to determine how many beacons are visible

**Comment by kylecorry31** [comment]
#### New debug build
- New astronomy graph (fixes inaccuracies with sun/moon positions)
- Support on astronomy page for places where sun/moon doesn't rise or set or does so out of order
- Set and rise times on astronomy page are ordered by occurrence instead of always being in the same order
- New setting to display the sun and moon on the compass

**Comment by kylecorry31** [comment]
#### New debug build
- Added compass mode setting to put more options there in case the legacy or experimental didn't work

**Comment by kylecorry31** [comment]
**New debug build**

- Added ability to put notes on new beacons (still need to add the ability to edit existing beacons and needs a little UI work - you can click the 'View Notes' text when navigating to a beacon)
- Improved the sea level pressure algorithm (needs some testing)
- Did some internal database changes - would be useful to see if anyone runs into any errors (looks good on my end)

**Comment by kylecorry31** [comment]
**New debug build**

- Improve the UI of the accuracy indicators (and adjusted navigation UI accordingly)
- Bug fix for older app versions upgrading to the new database

**Comment by kylecorry31** [comment]
**New debug build**
- Improve navigation UI
- Add estimated time to beacons
- Add accuracy tips (click on accuracy icons)
- Add setting to adjust weather forecast sensitivity
- Fix bug when trying to update the visibility of beacons

**Comment by kylecorry31** [comment]
**New debug build**
- Add weather information to the notification
- Add ability to edit beacons (long press from the beacon list)

**Comment by kylecorry31** [comment]
**New debug build**
- Added ability to hide the weather notification (in settings)
- Adjusted button placement on the navigation page

**Comment by kylecorry31** [comment]
**New debug build**
- Added flashlight to navigation tab (press once for light, a second time for SOS, and a third time for off) (runs in background as well)
- Fixed lag when opening TS

**Comment by kylecorry31** [comment]
**New debug build**
- Added ability to manually override location, altitude, and declination as well as tweak some more sensor values
- Improved speed calculation (ignoring inaccurate values)
- Added compass calibration dialog
- Persist selected beacon on close / tab change
- Added setting for displaying the pressure and tendency
- Added tendency to the weather page
- Added about section to settings

**Comment by kylecorry31** [comment]
**New debug build**
- Added setting to force pressure updates
- Adjusted tidal range calculation
- Added experimental features (inclinometer, tidal range)
- Potentially fixed a bug causing crashes on some Samsung devices

**Comment by kylecorry31** [comment]
**New debug build**
- Barometric altimeter
- Temperature and humidity
- More accurate astronomy data
- Show dusk/dawn times
- Pressure setpoint (tap and hold the current pressure on the weather tab)
- Show beacons within a certain radius
- Allow custom weather update interval
- Better Android 11 support
- Bug fixes

**Comment by kylecorry31** [comment]
**New debug build**
- Potential fixes for null pointer exceptions on some phones
- More translations

**Comment by kylecorry31** [comment]
**New debug build**
- Added beacon groups
- Changed sea level pressure algorithm - should be more accurate now (some advanced settings for this are still WIP)
- Reorganized settings
- Added animations when switching between views (not the tabs yet)
- Changed how readings are obtained in the background (adjustable with the weather settings - to test the new changes, you probably want to have "force weather updates" off and "update weather in foreground" on)
- Data storage changes
- Improved back button behavior

I'm looking for some people to test this version for a few days to verify the following features work better than the previous version:
- There should be less missed weather updates
- The sea level pressure conversion should be better - you can adjust the settings for this in the "Barometer and thermometer" settings

This version is not backward compatible with the previous version, therefore I made a new "Beta" build which will install alongside whatever version of Trail Sense you currently have, when you are done testing you can uninstall it and the real Trail Sense will be untouched. (The icon of the beta build is blue and has beta in the app name)

**Comment by kylecorry31** [comment]
There's a new beta version for 2.9.0

The following services are using a new background scheduling process and I would like feedback on if they are behaving the same. Please keep an eye out for if the GPS gets stuck on, I believe I fixed it and haven't experienced it in several days, but if it does happen I would really appreciate a bugreport.zip file. 
- Weather monitor (> 15 minutes)
- Backtrack (> 15 minutes)

Other new features:
- Lunar eclipses
- Improved solar panel alignment algorithm
- Astronomy details are clickable
- Supermoon (when you click an astronomy detail for the moon or long press the datepicker and search for supermoon)
- Weather data can be exported to CSV, which is useful for bug reports on the weather feature (weather settings) - the export does not contain sensitive data (pressures, altitudes, temperatures, humidity, and time)

The debug APK will overwrite your existing Trail Sense installation, and the beta APK will install as a separate application.

Thank you!

**Comment by kylecorry31** [comment]
There's a new beta version for 2.10.0

It contains the following changes:
- Log button on Weather tab to log a reading without running the background service
- Improved cloud tool
- Cloud scanner (experimental) - determines the type of cloud (leave feedback here: https://github.com/kylecorry31/Trail-Sense/issues/968)
- Material theme update
- Humidity history (for devices with a humidity sensor) - accessed through the thermometer tool
- A background compatibility mode (experimental) for devices having trouble with the background services (weather monitor, backtrack)

I only uploaded the beta APK since there were database changes meaning you couldn't revert to an older version of Trail Sense - the beta app will install as a separate app and will not affect any data you already have in TS (and can be uninstalled with no problem)

There are a few minor UI tweaks remaining before the final build which I plan to release in a day or two.

**Comment by FlatChest** [comment]
I've installed it with background compatibility mode enabled. I'll edit this post in a few hours to see if the weather monitor works now. Thanks again!

**Comment by qwerty287** [comment]
@kylecorry31 You could try to automate this process by using GH actions - currently you build the app, but do not use the output. You could improve this by changing the app's packages and similar things so that a beta/debug build is generated that can be installed along with the stable version, then build the app (what it's currently doing), sign the APK and upload the APK to Dropbox or something else (found a Dropbox uploader: https://github.com/marketplace/actions/dropbox-uploader).

You would have to find a way to store the keystore for signing, but GH actions should provide something like this. 


This would:
* allow simple testing without much effort
* use GH actions for something instead of just building the app and doing nothing with the APK
* allow testing of the latest commit's build

This would be kind of a win-win-situation: you don't have to build the app yourself + you can test the builds from the latest commits

**Comment by kylecorry31** [comment]
@qwerty287 that's a good idea, I'll play around with it. The only downside is that when I create a build for testing, I normally have specific things that I want to be tested, and can point out areas that are still in progress / broken so people know what to test or not, as to not waste their time.

**Comment by ACABMAN666** [comment]
> You can get debug builds for Trail Sense here: https://www.dropbox.com/sh/gplqslml3iyq2ec/AACn0Arv3KRHAUF1wCusmoZ2a?dl=0
> 
> I'll post a new comment here each time I build a debug build so you can download it and provide feedback on some new features while they are still in development.
> 
> If you are interested in getting a debug build, please leave a comment on this issue and I will create a new version and say what's in it. I stopped generating them automatically due to lack of feedback/engagement.

Hi, I'd be interested in testing the new features with the debug build

**Comment by kylecorry31** [comment]
@ACABMAN666 thank you!

I'm going to replace these debug builds with #1922 

As of right now, I don't have any new features in need of testing (nothing major this release) - but I will likely have something in the next release (full export), so I'll plan to complete #1922 in a couple weeks.

**Comment by ACABMAN666** [comment]
> @ACABMAN666 thank you!
> 
> I'm going to replace these debug builds with #1922
> 
> As of right now, I don't have any new features in need of testing (nothing major this release) - but I will likely have something in the next release (full export), so I'll plan to complete #1922 in a couple weeks.

Ok thanks for the information

**Comment by kylecorry31** [comment]
Hi all - nightly builds of Trail Sense are now available, see https://github.com/kylecorry31/Trail-Sense/discussions/1940 for more details.
