### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#743]
## Allow exporting of the following:
- [x] Database
- [x] Shared prefs
- [x] Files

## Actions
- [x] Export to zip
- [x] Import from zip
- [x] Disclaimer about only importing trusted zip files and that it will replace your current data (recommend creating a backup before restoring)
- [x] Close DB before backing up / restoring (maybe stopping all services temporarily)
- [x] Extract backup / restore functionality to commands
- [x] Extract folder / file selection helpers to Andromeda
- [x] Properly rename shared prefs file to work between build variants
- [x] Prevent restore from a newer version of Trail Sense to an older version
- [x] Restart app after backup, but return to the settings tab

## Testing
- [x] Verify it works between versions (with DB migrations + preference migrations)
- [x] Verify it works between build variants

**Comment by kylecorry31** [comment]
There should be the ability to import this file via onboarding or within settings

**Comment by s-kaczmarek** [comment]
Hi, seems like this feature was added to milestone 3.1.0 but to be honest, I can't find it in the options. How to export and import all the trail sense settings and data?

**Comment by kylecorry31** [comment]
Hi, this feature was added then removed from milestone 3.1.0. It has not been implemented yet.

**Comment by kylecorry31** [comment]
This feature is available in the nightly builds under Trail Sense settings
