### ISSUE TITLE
Add temperature convert tool

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#751]
Fahrenheit and Celsius

**Comment by qwerty287** [comment]
Probably you don't need it in an survival situation, but how about adding Kelvin? Just because it's the SI base unit and it's so simple to add :), just °C + 273,15

**Comment by kylecorry31** [comment]
@qwerty287 sorry, I'm going to skip on that - I don't see a use for Kelvin outside of scientific applications (even if it is really easy to add)
