### ISSUE TITLE
Support higher threshold values on metal detector

### ISSUE THREAD

**Issue by JensKorte** [kylecorry31/Trail-Sense#767]
The phone is a Galaxy S5 plus.

![Screenshot_20210705-184426_Trail_Sense](https://user-images.githubusercontent.com/2682123/124501310-99946d00-ddc1-11eb-82ed-5bd24848a670.png)

**Comment by JensKorte** [comment]
Calibration has a max value of 125.

**Comment by kylecorry31** [comment]
I originally intended calibration to be for only removing Earth's magnetic field as this is intended for use outdoors. I'm assuming you are using this indoors to get this result?

I'll consider allowing the calibration of arbitrary magnetic fields with higher strengths though

**Comment by JensKorte** [comment]
> I'm assuming you are using this indoors to get this result?

Yes, you are right ;)

**Comment by kylecorry31** [comment]
The metal detector tool's threshold was recently redesigned to be a relative threshold, so I think this is resolved now. If not, feel free to comment here and I'll open it back up.
