### ISSUE TITLE
Astronomy page is cluttered in small screens

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#77]

**Comment by sethtara** [comment]
Is this issue for : https://github.com/kylecorry31/Trail-Sense/issues/74#issuecomment-631418867

**Comment by kylecorry31** [comment]
Here's another option to get that text out of the way (it follows the moon as it moves around):

![Screenshot_1590001958](https://user-images.githubusercontent.com/5938560/82487505-6e12ce00-9aac-11ea-89a4-62eae462527b.png)

**Comment by sethtara** [comment]
### That's perfect
