### ISSUE TITLE
Possible 4.x port?

### ISSUE THREAD

**Issue by tiffytoffee** [kylecorry31/Trail-Sense#778]
Hi, first of all thank you very much for the app; it's extremely useful and one of my favourite apps to use.

Sadly, most of my development is with Python and I know very little about Java.
Is it possible to port this app to e.g. 4.4.4 KitKat to use with my old phones, potentially through removing some features?

If I could get some info on what actual features / APIs TS targets that are API>=23, I wouldn't mind trying to understand / how to port it myself but I hardly ever work with Java let alone Android apps.

Again, thanks for the app Kyle and apologies if this is a stupid request.

The phone I specifically have is SM-G357FZ (Ace 4 "Style"), and as my secondary phone running 4.4.4 it's a good companion alongside my SM-G973F/DS (S10) and this app would be a brilliant way to utilise it more.

**Comment by kylecorry31** [comment]
Hi, thank you! Unfortunately a port to 4.X Android isn't possible for Trail Sense - it relies on too many features that were first introduced in 5.0 for core behavior (and several from 6.0 - a port to 5.0 might be possible, though it is going to be a lot of work). I've attempted a backport before: https://github.com/kylecorry31/Trail-Sense/issues/322 and https://github.com/kylecorry31/Trail-Sense/issues/78.
