### ISSUE TITLE
Support OS National Grid format

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#788]
https://www.movable-type.co.uk/scripts/latlong-os-gridref.html

https://getoutside.ordnancesurvey.co.uk/guides/beginners-guide-to-grid-references/

https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid

(OSGB36)

Fall back to Lat/Lon outside of grid area.

**Comment by Lee-Carre** [comment]
[OSGB Grid Reference to OSM Map](//osm.mathmos.net/osgb2osm/)

**Comment by kylecorry31** [comment]
@Lee-Carre is your suggestion a fully numeric OSGB format?

**Comment by Lee-Carre** [comment]
@kylecorry31

Not explicitly (but if you want to implement that, I won't complain). My intention was simply to drop a pointer to what might be a useful reference / tool (for verification), and for when the maps module is non-experimental (to display the result).

If not useful, then ignore / delete 🙂.
