### ISSUE TITLE
Add zoom buttons to map

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#795]

**Comment by qwerty287** [comment]
I could open a PR to fix this, is this ok?

**Comment by kylecorry31** [comment]
@qwerty287 thanks! That is fine, can you add them to the bottom left of the screen and be at 0.86 alpha/opacity (or 0.6, whichever works best). There is currently a double-tap to zoom functionality, I imagine the buttons could use the same logic
