### ISSUE TITLE
Center map to current location

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#798]
A button when clicked will center the map (at current zoom level) on the user.

- [x] Center location on screen
- [x] Zoom to location

**Comment by Heptameron123** [comment]
If this feature is not added then, I support and strengthen! This is necessary in the field conditions.

**Comment by kylecorry31** [comment]
@Heptameron123 this is not added yet and is it not currently planned for version 3.0.0 (the upcoming release, probably later this month). I might add it for the 3.1.0 release, but that would likely be next month. If there's a pull request for it, I might be able to add it to the 3.0.0 release.
