### ISSUE TITLE
pedometer tile resets preference

### ISSUE THREAD

**Issue by dalb8** [kylecorry31/Trail-Sense#802]
I added the pedometer quick settings tile. At first it did nothing, until I granted the permission. so far so good. Then I set the odometer to pedometer in trail sense settings. It seems that each time I toggle the quick settings tile the odometer gets reset to gps.

Version 2.3.3. . Android 10

**Comment by dalb8** [comment]
If the function of this tile is to switch between gps and pedometer then please close :-)

**Comment by kylecorry31** [comment]
The functionality of that tile is to switch to GPS, which is used as a passive odometer that updates every time a GPS fix is acquired (therefore uses no additional battery)
