### ISSUE TITLE
Add ruler calibration

### ISSUE THREAD

**Issue by pr0gr8mm3r** [kylecorry31/Trail-Sense#81]
On my device each cm the ruler displays is only about 0,87cm when I measure it. An option in the settings or something similar could allow the user to measure a length and enter what he measured, similar to this:
![Screenshot_20200523-093427](https://user-images.githubusercontent.com/37022952/82724790-ecec4e80-9cd8-11ea-9fe0-f7ee9796011a.png)
(Screenshot from app called "Tape Measure" on F-Droid)

**Comment by kylecorry31** [comment]
This definitely needs some work regarding how user friendly it is (and the wording / description is far from perfect), but at least it will resolve this issue for the time being (it is unit independent).

![Screenshot_1590235663](https://user-images.githubusercontent.com/5938560/82730323-bd374980-9ccc-11ea-90c4-743a656a83d1.png)
