### ISSUE TITLE
Add option to include leading zero (hour) in times

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#831]
- [x] Add toggle to unit settings for "Add leading zero to time" (below the "Use 24-hour format" setting)
- [x] Add property to UserPreferences (use BooleanPreference, see backtrackSaveCellHistory as an example)
- [x] Update FormatService.formatTime to use the leading zero preference
- [x] Default is false

Examples:
- 3:00 AM -> 03:00 AM
- 05:00 -> 05:00

**Comment by Portagoras** [comment]
Heyho, I will be on vacation soon-ish and am looking for things todo. Would be glad if you would describe the issue closer.

**Comment by kylecorry31** [comment]
@Portagoras thank you, I have updated the description of this issue with more details

**Comment by Portagoras** [comment]
Many thanks!
