### ISSUE TITLE
Bad layout in splitscreen mode

### ISSUE THREAD

**Issue by qwerty287** [kylecorry31/Trail-Sense#834]
If you don't want to change the layout to fit the splitscreen mode, you can disable it: https://stackoverflow.com/questions/40259027/disable-split-screen-android

![Screenshot_20210803-090901](https://user-images.githubusercontent.com/80460567/127973150-ac3f97eb-f679-4ed2-af93-e2a20da65d41.png)

**Comment by kylecorry31** [comment]
Thanks, I'll disable split screen
