### ISSUE TITLE
Linear compass should be displayed in landscape orientation

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#84]
Right now it's only displayed when the phone is in portrait mode

**Comment by kylecorry31** [comment]
I didn't put it in landscape mode yet because I think Trail Sense would need to support landscape in general for that to make sense (or else most of the UI will be sideways). I'll create an issue for adding landscape support (although it will be low priority)

**Comment by kylecorry31** [comment]
Not going to support landscape orientation - too much to port over.
