### ISSUE TITLE
Option to show only beacons within a certain distance

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#90]
Not sure how this would combine with other visibility settings

**Comment by kylecorry31** [comment]
I was thinking of adding this, I'll have to explore some ideas here

**Comment by kylecorry31** [comment]
For now just to get this in place, I may need to do the following:
1. User clicks on max beacon distance setting
2. Switches to a new screen where they can enter the distance + select the unit that they are providing the distance in (respects distance unit settings)
3. Clicks done, brings them back to the setting list

I know that breaks the user experience of the settings page, but it is difficult to deal with different units in the settings screen - I'll eventually revisit and create a custom dialog where they can set all this stuff.
