### ISSUE TITLE
Better display for when sun doesn't set/rise

### ISSUE THREAD

**Issue by swedneck** [kylecorry31/Trail-Sense#91]
Currently if you live somewhere the sun doesn't rise/set for a full day the astronomy page simply shows the rise/set times as 00:00/23:59

It should instead make it obvious that the sun simply doesn't rise/set that day.

**Comment by kylecorry31** [comment]
Definitely, I recognize those as the default values I'm returning in those cases - I can make it more clear (like the moonrise/set dash to indicate it doesn't happen)

**Comment by kylecorry31** [comment]
Still have some more work to do here (like when sun rises or sets, but not both - and fixing that position issue)

![Screenshot_1590449205](https://user-images.githubusercontent.com/5938560/82847734-ba4f7b00-9ebd-11ea-8850-087775470912.png)
