### ISSUE TITLE
Pedometer without persistent notification

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#928]
Other fitness / pedometer apps do it, I want to research more how to let the pedometer run without a foreground service and then allow the user to choose to have the notification or not.

**Comment by kylecorry31** [comment]
From my research, it appears that this needs to run as a foreground service (so needs to have a notification) - I will experiment with what happens if the user disables the notification from system settings (and recommend doing that if it works)

**Comment by kylecorry31** [comment]
Disabling the notification from the system settings allows this to work and has been added to the FAQ

**Comment by Lee-Carre** [comment]
> Disabling the notification from the system settings …

Doesn't that leave the foreground service at risk for being killed? To my understanding, the notification is what prevents this.

**Comment by kylecorry31** [comment]
As far as I can tell it stays active (I let it run for 3 days, opening TS here and there though). I also have had the weather and backtrack channels disabled for close to a year, and didn't have issues - maybe Android just hides the notification from the user, but treats it as an active notification/foreground service?

I can do more research just to be sure though.
