### ISSUE TITLE
Material theme styling issues

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#940]
- [x] Some FABs have a yellow border
- [x] Some quick actions have the wrong tint/background color
- [x] Text on primary color buttons should be the same (probably white - I'll check the contract score first)
- [x] Light theme causes system top bar to become blue

**Comment by ebraminio** [comment]
>  Light theme causes system top bar to become blue

Its current default is,
```
        <item name="android:statusBarColor">?attr/colorPrimaryDark</item>
```

What would the intended behavior here? I thought somehow its default is good somehow.

**Comment by ebraminio** [comment]
Feels like the previous behavior `<item name="android:statusBarColor">#40000000</item>`

**Comment by ebraminio** [comment]
>  Some FABs have a yellow border

A screenshot for this one would be nice :)

**Comment by kylecorry31** [comment]
![Screenshot_20210927-091110](https://user-images.githubusercontent.com/5938560/134915066-cb98a8c7-baa0-4a67-9a9a-a57e34e0a81d.png)

Thanks! Here's a screenshot of the packing list (note the issue isn't on the navigation/beacon page) - I didn't have time to debug it at all this morning

**Comment by ebraminio** [comment]
So this can be closed now I'd guess :)

**Comment by kylecorry31** [comment]
@ebraminio awesome, thanks for the help!
