### ISSUE TITLE
Trail Sense icon on default splash screen of Android 12 

### ISSUE THREAD

**Issue by ebraminio** [kylecorry31/Trail-Sense#951]
Android 12 provides a default splash screen for apps and Trail Sense will look like this with that default splash screen,

https://user-images.githubusercontent.com/833473/135076762-785e3702-91c2-4c0e-b166-e8611db3385a.mov

(press pause in 0:02, trail sense icon's background will be the same with the splash screen default)

Not sure what can be done here, maybe it will be fixed in the public release of Android 12 or maybe some considerations here would be nice.

**Comment by kylecorry31** [comment]
Yeah, I noticed that - I didn't look into it yet since it seemed minor, but I'm assuming I need to configure the background color somehow
