### ISSUE TITLE
QR transmission

### ISSUE THREAD

**Issue by kylecorry31** [kylecorry31/Trail-Sense#960]
- [x] User can enter text to share
- [x] User can generate a QR code containing the text
- [x] User can scan a QR code to retrieve text
- [x] User can turn on torch while scanning
- [x] User can zoom in while scanning
- [x] User can copy the scanned text
- [x] User can save scanned text as note
- [x] If scanned text is a URL, allow opening in browser
- [x] If scanned text is a coordinate, allow creating a beacon

**Comment by kylecorry31** [comment]
This could also be used as a way to send text between devices:

Have a second tab for a QR code that can be scanned

**Comment by Lee-Carre** [comment]
For those of us who like using (task-)specific tools, then please make it possible (viz via intents) for inter-process communication. Both for acquiring the results of a scan, and generating codes from (textual\|human-readable) input. Possibly also transmitting the result (though there's yet other apps for that specific (sub-)task).

I'm thinking specifically of [Binary Eye](http://www.github.com/markusfisch/BinaryEye), here.

**Comment by kylecorry31** [comment]
@Lee-Carre good idea, here's the new issue to track that: https://github.com/kylecorry31/Trail-Sense/issues/1086

As for transmitting the result of the scan, I'm currently supporting location and web URL intents (with an intent chooser, so the user can choose the app to open them with).
